
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ManagerNotificationPreferences` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ManagerNotificationPreferences
 * 
 */
export type ManagerNotificationPreferencesModel = runtime.Types.Result.DefaultSelection<Prisma.$ManagerNotificationPreferencesPayload>

export type AggregateManagerNotificationPreferences = {
  _count: ManagerNotificationPreferencesCountAggregateOutputType | null
  _min: ManagerNotificationPreferencesMinAggregateOutputType | null
  _max: ManagerNotificationPreferencesMaxAggregateOutputType | null
}

export type ManagerNotificationPreferencesMinAggregateOutputType = {
  id: string | null
  managerId: string | null
  notificationTypeId: string | null
  createdAt: Date | null
}

export type ManagerNotificationPreferencesMaxAggregateOutputType = {
  id: string | null
  managerId: string | null
  notificationTypeId: string | null
  createdAt: Date | null
}

export type ManagerNotificationPreferencesCountAggregateOutputType = {
  id: number
  managerId: number
  notificationTypeId: number
  createdAt: number
  _all: number
}


export type ManagerNotificationPreferencesMinAggregateInputType = {
  id?: true
  managerId?: true
  notificationTypeId?: true
  createdAt?: true
}

export type ManagerNotificationPreferencesMaxAggregateInputType = {
  id?: true
  managerId?: true
  notificationTypeId?: true
  createdAt?: true
}

export type ManagerNotificationPreferencesCountAggregateInputType = {
  id?: true
  managerId?: true
  notificationTypeId?: true
  createdAt?: true
  _all?: true
}

export type ManagerNotificationPreferencesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManagerNotificationPreferences to aggregate.
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagerNotificationPreferences to fetch.
   */
  orderBy?: Prisma.ManagerNotificationPreferencesOrderByWithRelationInput | Prisma.ManagerNotificationPreferencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagerNotificationPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagerNotificationPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ManagerNotificationPreferences
  **/
  _count?: true | ManagerNotificationPreferencesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManagerNotificationPreferencesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManagerNotificationPreferencesMaxAggregateInputType
}

export type GetManagerNotificationPreferencesAggregateType<T extends ManagerNotificationPreferencesAggregateArgs> = {
      [P in keyof T & keyof AggregateManagerNotificationPreferences]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManagerNotificationPreferences[P]>
    : Prisma.GetScalarType<T[P], AggregateManagerNotificationPreferences[P]>
}




export type ManagerNotificationPreferencesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  orderBy?: Prisma.ManagerNotificationPreferencesOrderByWithAggregationInput | Prisma.ManagerNotificationPreferencesOrderByWithAggregationInput[]
  by: Prisma.ManagerNotificationPreferencesScalarFieldEnum[] | Prisma.ManagerNotificationPreferencesScalarFieldEnum
  having?: Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManagerNotificationPreferencesCountAggregateInputType | true
  _min?: ManagerNotificationPreferencesMinAggregateInputType
  _max?: ManagerNotificationPreferencesMaxAggregateInputType
}

export type ManagerNotificationPreferencesGroupByOutputType = {
  id: string
  managerId: string
  notificationTypeId: string
  createdAt: Date
  _count: ManagerNotificationPreferencesCountAggregateOutputType | null
  _min: ManagerNotificationPreferencesMinAggregateOutputType | null
  _max: ManagerNotificationPreferencesMaxAggregateOutputType | null
}

type GetManagerNotificationPreferencesGroupByPayload<T extends ManagerNotificationPreferencesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManagerNotificationPreferencesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManagerNotificationPreferencesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManagerNotificationPreferencesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManagerNotificationPreferencesGroupByOutputType[P]>
      }
    >
  >



export type ManagerNotificationPreferencesWhereInput = {
  AND?: Prisma.ManagerNotificationPreferencesWhereInput | Prisma.ManagerNotificationPreferencesWhereInput[]
  OR?: Prisma.ManagerNotificationPreferencesWhereInput[]
  NOT?: Prisma.ManagerNotificationPreferencesWhereInput | Prisma.ManagerNotificationPreferencesWhereInput[]
  id?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  managerId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  notificationTypeId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  createdAt?: Prisma.DateTimeFilter<"ManagerNotificationPreferences"> | Date | string
  manager?: Prisma.XOR<Prisma.ManagerScalarRelationFilter, Prisma.ManagerWhereInput>
  notificationType?: Prisma.XOR<Prisma.NotificationTypeScalarRelationFilter, Prisma.NotificationTypeWhereInput>
}

export type ManagerNotificationPreferencesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  notificationTypeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  manager?: Prisma.ManagerOrderByWithRelationInput
  notificationType?: Prisma.NotificationTypeOrderByWithRelationInput
}

export type ManagerNotificationPreferencesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  managerId_notificationTypeId?: Prisma.ManagerNotificationPreferencesManagerIdNotificationTypeIdCompoundUniqueInput
  AND?: Prisma.ManagerNotificationPreferencesWhereInput | Prisma.ManagerNotificationPreferencesWhereInput[]
  OR?: Prisma.ManagerNotificationPreferencesWhereInput[]
  NOT?: Prisma.ManagerNotificationPreferencesWhereInput | Prisma.ManagerNotificationPreferencesWhereInput[]
  managerId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  notificationTypeId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  createdAt?: Prisma.DateTimeFilter<"ManagerNotificationPreferences"> | Date | string
  manager?: Prisma.XOR<Prisma.ManagerScalarRelationFilter, Prisma.ManagerWhereInput>
  notificationType?: Prisma.XOR<Prisma.NotificationTypeScalarRelationFilter, Prisma.NotificationTypeWhereInput>
}, "id" | "managerId_notificationTypeId">

export type ManagerNotificationPreferencesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  notificationTypeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ManagerNotificationPreferencesCountOrderByAggregateInput
  _max?: Prisma.ManagerNotificationPreferencesMaxOrderByAggregateInput
  _min?: Prisma.ManagerNotificationPreferencesMinOrderByAggregateInput
}

export type ManagerNotificationPreferencesScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput | Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput | Prisma.ManagerNotificationPreferencesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ManagerNotificationPreferences"> | string
  managerId?: Prisma.StringWithAggregatesFilter<"ManagerNotificationPreferences"> | string
  notificationTypeId?: Prisma.StringWithAggregatesFilter<"ManagerNotificationPreferences"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ManagerNotificationPreferences"> | Date | string
}

export type ManagerNotificationPreferencesCreateInput = {
  id?: string
  createdAt?: Date | string
  manager: Prisma.ManagerCreateNestedOneWithoutPreferencesInput
  notificationType: Prisma.NotificationTypeCreateNestedOneWithoutPreferencesInput
}

export type ManagerNotificationPreferencesUncheckedCreateInput = {
  id?: string
  managerId: string
  notificationTypeId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  manager?: Prisma.ManagerUpdateOneRequiredWithoutPreferencesNestedInput
  notificationType?: Prisma.NotificationTypeUpdateOneRequiredWithoutPreferencesNestedInput
}

export type ManagerNotificationPreferencesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.StringFieldUpdateOperationsInput | string
  notificationTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesCreateManyInput = {
  id?: string
  managerId: string
  notificationTypeId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.StringFieldUpdateOperationsInput | string
  notificationTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesListRelationFilter = {
  every?: Prisma.ManagerNotificationPreferencesWhereInput
  some?: Prisma.ManagerNotificationPreferencesWhereInput
  none?: Prisma.ManagerNotificationPreferencesWhereInput
}

export type ManagerNotificationPreferencesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ManagerNotificationPreferencesManagerIdNotificationTypeIdCompoundUniqueInput = {
  managerId: string
  notificationTypeId: string
}

export type ManagerNotificationPreferencesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  notificationTypeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ManagerNotificationPreferencesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  notificationTypeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ManagerNotificationPreferencesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  managerId?: Prisma.SortOrder
  notificationTypeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ManagerNotificationPreferencesCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput> | Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyManagerInputEnvelope
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
}

export type ManagerNotificationPreferencesUncheckedCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput> | Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyManagerInputEnvelope
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
}

export type ManagerNotificationPreferencesUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput> | Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyManagerInputEnvelope
  set?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  disconnect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  delete?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  update?: Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
}

export type ManagerNotificationPreferencesUncheckedUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput> | Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyManagerInputEnvelope
  set?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  disconnect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  delete?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  update?: Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutManagerInput | Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
}

export type ManagerNotificationPreferencesCreateNestedManyWithoutNotificationTypeInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput> | Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInputEnvelope
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
}

export type ManagerNotificationPreferencesUncheckedCreateNestedManyWithoutNotificationTypeInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput> | Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInputEnvelope
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
}

export type ManagerNotificationPreferencesUpdateManyWithoutNotificationTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput> | Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput[]
  upsert?: Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutNotificationTypeInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInputEnvelope
  set?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  disconnect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  delete?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  update?: Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutNotificationTypeInput[]
  updateMany?: Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutNotificationTypeInput[]
  deleteMany?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
}

export type ManagerNotificationPreferencesUncheckedUpdateManyWithoutNotificationTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput> | Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput[] | Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput[]
  connectOrCreate?: Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput[]
  upsert?: Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutNotificationTypeInput[]
  createMany?: Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInputEnvelope
  set?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  disconnect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  delete?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  connect?: Prisma.ManagerNotificationPreferencesWhereUniqueInput | Prisma.ManagerNotificationPreferencesWhereUniqueInput[]
  update?: Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutNotificationTypeInput[]
  updateMany?: Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutNotificationTypeInput | Prisma.ManagerNotificationPreferencesUpdateManyWithWhereWithoutNotificationTypeInput[]
  deleteMany?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
}

export type ManagerNotificationPreferencesCreateWithoutManagerInput = {
  id?: string
  createdAt?: Date | string
  notificationType: Prisma.NotificationTypeCreateNestedOneWithoutPreferencesInput
}

export type ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput = {
  id?: string
  notificationTypeId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesCreateOrConnectWithoutManagerInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  create: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput>
}

export type ManagerNotificationPreferencesCreateManyManagerInputEnvelope = {
  data: Prisma.ManagerNotificationPreferencesCreateManyManagerInput | Prisma.ManagerNotificationPreferencesCreateManyManagerInput[]
  skipDuplicates?: boolean
}

export type ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutManagerInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  update: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateWithoutManagerInput>
  create: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutManagerInput>
}

export type ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutManagerInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateWithoutManagerInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateWithoutManagerInput>
}

export type ManagerNotificationPreferencesUpdateManyWithWhereWithoutManagerInput = {
  where: Prisma.ManagerNotificationPreferencesScalarWhereInput
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateManyMutationInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateManyWithoutManagerInput>
}

export type ManagerNotificationPreferencesScalarWhereInput = {
  AND?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
  OR?: Prisma.ManagerNotificationPreferencesScalarWhereInput[]
  NOT?: Prisma.ManagerNotificationPreferencesScalarWhereInput | Prisma.ManagerNotificationPreferencesScalarWhereInput[]
  id?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  managerId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  notificationTypeId?: Prisma.StringFilter<"ManagerNotificationPreferences"> | string
  createdAt?: Prisma.DateTimeFilter<"ManagerNotificationPreferences"> | Date | string
}

export type ManagerNotificationPreferencesCreateWithoutNotificationTypeInput = {
  id?: string
  createdAt?: Date | string
  manager: Prisma.ManagerCreateNestedOneWithoutPreferencesInput
}

export type ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput = {
  id?: string
  managerId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesCreateOrConnectWithoutNotificationTypeInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  create: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput>
}

export type ManagerNotificationPreferencesCreateManyNotificationTypeInputEnvelope = {
  data: Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInput | Prisma.ManagerNotificationPreferencesCreateManyNotificationTypeInput[]
  skipDuplicates?: boolean
}

export type ManagerNotificationPreferencesUpsertWithWhereUniqueWithoutNotificationTypeInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  update: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateWithoutNotificationTypeInput>
  create: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedCreateWithoutNotificationTypeInput>
}

export type ManagerNotificationPreferencesUpdateWithWhereUniqueWithoutNotificationTypeInput = {
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateWithoutNotificationTypeInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateWithoutNotificationTypeInput>
}

export type ManagerNotificationPreferencesUpdateManyWithWhereWithoutNotificationTypeInput = {
  where: Prisma.ManagerNotificationPreferencesScalarWhereInput
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateManyMutationInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateManyWithoutNotificationTypeInput>
}

export type ManagerNotificationPreferencesCreateManyManagerInput = {
  id?: string
  notificationTypeId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notificationType?: Prisma.NotificationTypeUpdateOneRequiredWithoutPreferencesNestedInput
}

export type ManagerNotificationPreferencesUncheckedUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notificationTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesUncheckedUpdateManyWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notificationTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesCreateManyNotificationTypeInput = {
  id?: string
  managerId: string
  createdAt?: Date | string
}

export type ManagerNotificationPreferencesUpdateWithoutNotificationTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  manager?: Prisma.ManagerUpdateOneRequiredWithoutPreferencesNestedInput
}

export type ManagerNotificationPreferencesUncheckedUpdateWithoutNotificationTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagerNotificationPreferencesUncheckedUpdateManyWithoutNotificationTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  managerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ManagerNotificationPreferencesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  managerId?: boolean
  notificationTypeId?: boolean
  createdAt?: boolean
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["managerNotificationPreferences"]>

export type ManagerNotificationPreferencesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  managerId?: boolean
  notificationTypeId?: boolean
  createdAt?: boolean
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["managerNotificationPreferences"]>

export type ManagerNotificationPreferencesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  managerId?: boolean
  notificationTypeId?: boolean
  createdAt?: boolean
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["managerNotificationPreferences"]>

export type ManagerNotificationPreferencesSelectScalar = {
  id?: boolean
  managerId?: boolean
  notificationTypeId?: boolean
  createdAt?: boolean
}

export type ManagerNotificationPreferencesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "managerId" | "notificationTypeId" | "createdAt", ExtArgs["result"]["managerNotificationPreferences"]>
export type ManagerNotificationPreferencesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}
export type ManagerNotificationPreferencesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}
export type ManagerNotificationPreferencesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  manager?: boolean | Prisma.ManagerDefaultArgs<ExtArgs>
  notificationType?: boolean | Prisma.NotificationTypeDefaultArgs<ExtArgs>
}

export type $ManagerNotificationPreferencesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ManagerNotificationPreferences"
  objects: {
    manager: Prisma.$ManagerPayload<ExtArgs>
    notificationType: Prisma.$NotificationTypePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    managerId: string
    notificationTypeId: string
    createdAt: Date
  }, ExtArgs["result"]["managerNotificationPreferences"]>
  composites: {}
}

export type ManagerNotificationPreferencesGetPayload<S extends boolean | null | undefined | ManagerNotificationPreferencesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload, S>

export type ManagerNotificationPreferencesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManagerNotificationPreferencesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManagerNotificationPreferencesCountAggregateInputType | true
  }

export interface ManagerNotificationPreferencesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ManagerNotificationPreferences'], meta: { name: 'ManagerNotificationPreferences' } }
  /**
   * Find zero or one ManagerNotificationPreferences that matches the filter.
   * @param {ManagerNotificationPreferencesFindUniqueArgs} args - Arguments to find a ManagerNotificationPreferences
   * @example
   * // Get one ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManagerNotificationPreferencesFindUniqueArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ManagerNotificationPreferences that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManagerNotificationPreferencesFindUniqueOrThrowArgs} args - Arguments to find a ManagerNotificationPreferences
   * @example
   * // Get one ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManagerNotificationPreferencesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManagerNotificationPreferences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesFindFirstArgs} args - Arguments to find a ManagerNotificationPreferences
   * @example
   * // Get one ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManagerNotificationPreferencesFindFirstArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManagerNotificationPreferences that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesFindFirstOrThrowArgs} args - Arguments to find a ManagerNotificationPreferences
   * @example
   * // Get one ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManagerNotificationPreferencesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ManagerNotificationPreferences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findMany()
   * 
   * // Get first 10 ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const managerNotificationPreferencesWithIdOnly = await prisma.managerNotificationPreferences.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManagerNotificationPreferencesFindManyArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesCreateArgs} args - Arguments to create a ManagerNotificationPreferences.
   * @example
   * // Create one ManagerNotificationPreferences
   * const ManagerNotificationPreferences = await prisma.managerNotificationPreferences.create({
   *   data: {
   *     // ... data to create a ManagerNotificationPreferences
   *   }
   * })
   * 
   */
  create<T extends ManagerNotificationPreferencesCreateArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesCreateArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesCreateManyArgs} args - Arguments to create many ManagerNotificationPreferences.
   * @example
   * // Create many ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManagerNotificationPreferencesCreateManyArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ManagerNotificationPreferences and returns the data saved in the database.
   * @param {ManagerNotificationPreferencesCreateManyAndReturnArgs} args - Arguments to create many ManagerNotificationPreferences.
   * @example
   * // Create many ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ManagerNotificationPreferences and only return the `id`
   * const managerNotificationPreferencesWithIdOnly = await prisma.managerNotificationPreferences.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManagerNotificationPreferencesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesDeleteArgs} args - Arguments to delete one ManagerNotificationPreferences.
   * @example
   * // Delete one ManagerNotificationPreferences
   * const ManagerNotificationPreferences = await prisma.managerNotificationPreferences.delete({
   *   where: {
   *     // ... filter to delete one ManagerNotificationPreferences
   *   }
   * })
   * 
   */
  delete<T extends ManagerNotificationPreferencesDeleteArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesDeleteArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesUpdateArgs} args - Arguments to update one ManagerNotificationPreferences.
   * @example
   * // Update one ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManagerNotificationPreferencesUpdateArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesUpdateArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesDeleteManyArgs} args - Arguments to filter ManagerNotificationPreferences to delete.
   * @example
   * // Delete a few ManagerNotificationPreferences
   * const { count } = await prisma.managerNotificationPreferences.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManagerNotificationPreferencesDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManagerNotificationPreferencesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManagerNotificationPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManagerNotificationPreferencesUpdateManyArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManagerNotificationPreferences and returns the data updated in the database.
   * @param {ManagerNotificationPreferencesUpdateManyAndReturnArgs} args - Arguments to update many ManagerNotificationPreferences.
   * @example
   * // Update many ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ManagerNotificationPreferences and only return the `id`
   * const managerNotificationPreferencesWithIdOnly = await prisma.managerNotificationPreferences.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManagerNotificationPreferencesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ManagerNotificationPreferences.
   * @param {ManagerNotificationPreferencesUpsertArgs} args - Arguments to update or create a ManagerNotificationPreferences.
   * @example
   * // Update or create a ManagerNotificationPreferences
   * const managerNotificationPreferences = await prisma.managerNotificationPreferences.upsert({
   *   create: {
   *     // ... data to create a ManagerNotificationPreferences
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ManagerNotificationPreferences we want to update
   *   }
   * })
   */
  upsert<T extends ManagerNotificationPreferencesUpsertArgs>(args: Prisma.SelectSubset<T, ManagerNotificationPreferencesUpsertArgs<ExtArgs>>): Prisma.Prisma__ManagerNotificationPreferencesClient<runtime.Types.Result.GetResult<Prisma.$ManagerNotificationPreferencesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ManagerNotificationPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesCountArgs} args - Arguments to filter ManagerNotificationPreferences to count.
   * @example
   * // Count the number of ManagerNotificationPreferences
   * const count = await prisma.managerNotificationPreferences.count({
   *   where: {
   *     // ... the filter for the ManagerNotificationPreferences we want to count
   *   }
   * })
  **/
  count<T extends ManagerNotificationPreferencesCountArgs>(
    args?: Prisma.Subset<T, ManagerNotificationPreferencesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManagerNotificationPreferencesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ManagerNotificationPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManagerNotificationPreferencesAggregateArgs>(args: Prisma.Subset<T, ManagerNotificationPreferencesAggregateArgs>): Prisma.PrismaPromise<GetManagerNotificationPreferencesAggregateType<T>>

  /**
   * Group by ManagerNotificationPreferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagerNotificationPreferencesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManagerNotificationPreferencesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManagerNotificationPreferencesGroupByArgs['orderBy'] }
      : { orderBy?: ManagerNotificationPreferencesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManagerNotificationPreferencesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManagerNotificationPreferencesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ManagerNotificationPreferences model
 */
readonly fields: ManagerNotificationPreferencesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ManagerNotificationPreferences.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManagerNotificationPreferencesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  manager<T extends Prisma.ManagerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ManagerDefaultArgs<ExtArgs>>): Prisma.Prisma__ManagerClient<runtime.Types.Result.GetResult<Prisma.$ManagerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  notificationType<T extends Prisma.NotificationTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NotificationTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__NotificationTypeClient<runtime.Types.Result.GetResult<Prisma.$NotificationTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ManagerNotificationPreferences model
 */
export interface ManagerNotificationPreferencesFieldRefs {
  readonly id: Prisma.FieldRef<"ManagerNotificationPreferences", 'String'>
  readonly managerId: Prisma.FieldRef<"ManagerNotificationPreferences", 'String'>
  readonly notificationTypeId: Prisma.FieldRef<"ManagerNotificationPreferences", 'String'>
  readonly createdAt: Prisma.FieldRef<"ManagerNotificationPreferences", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ManagerNotificationPreferences findUnique
 */
export type ManagerNotificationPreferencesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter, which ManagerNotificationPreferences to fetch.
   */
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
}

/**
 * ManagerNotificationPreferences findUniqueOrThrow
 */
export type ManagerNotificationPreferencesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter, which ManagerNotificationPreferences to fetch.
   */
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
}

/**
 * ManagerNotificationPreferences findFirst
 */
export type ManagerNotificationPreferencesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter, which ManagerNotificationPreferences to fetch.
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagerNotificationPreferences to fetch.
   */
  orderBy?: Prisma.ManagerNotificationPreferencesOrderByWithRelationInput | Prisma.ManagerNotificationPreferencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManagerNotificationPreferences.
   */
  cursor?: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagerNotificationPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagerNotificationPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManagerNotificationPreferences.
   */
  distinct?: Prisma.ManagerNotificationPreferencesScalarFieldEnum | Prisma.ManagerNotificationPreferencesScalarFieldEnum[]
}

/**
 * ManagerNotificationPreferences findFirstOrThrow
 */
export type ManagerNotificationPreferencesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter, which ManagerNotificationPreferences to fetch.
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagerNotificationPreferences to fetch.
   */
  orderBy?: Prisma.ManagerNotificationPreferencesOrderByWithRelationInput | Prisma.ManagerNotificationPreferencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManagerNotificationPreferences.
   */
  cursor?: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagerNotificationPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagerNotificationPreferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManagerNotificationPreferences.
   */
  distinct?: Prisma.ManagerNotificationPreferencesScalarFieldEnum | Prisma.ManagerNotificationPreferencesScalarFieldEnum[]
}

/**
 * ManagerNotificationPreferences findMany
 */
export type ManagerNotificationPreferencesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter, which ManagerNotificationPreferences to fetch.
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagerNotificationPreferences to fetch.
   */
  orderBy?: Prisma.ManagerNotificationPreferencesOrderByWithRelationInput | Prisma.ManagerNotificationPreferencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ManagerNotificationPreferences.
   */
  cursor?: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagerNotificationPreferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagerNotificationPreferences.
   */
  skip?: number
  distinct?: Prisma.ManagerNotificationPreferencesScalarFieldEnum | Prisma.ManagerNotificationPreferencesScalarFieldEnum[]
}

/**
 * ManagerNotificationPreferences create
 */
export type ManagerNotificationPreferencesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * The data needed to create a ManagerNotificationPreferences.
   */
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateInput, Prisma.ManagerNotificationPreferencesUncheckedCreateInput>
}

/**
 * ManagerNotificationPreferences createMany
 */
export type ManagerNotificationPreferencesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ManagerNotificationPreferences.
   */
  data: Prisma.ManagerNotificationPreferencesCreateManyInput | Prisma.ManagerNotificationPreferencesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManagerNotificationPreferences createManyAndReturn
 */
export type ManagerNotificationPreferencesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * The data used to create many ManagerNotificationPreferences.
   */
  data: Prisma.ManagerNotificationPreferencesCreateManyInput | Prisma.ManagerNotificationPreferencesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ManagerNotificationPreferences update
 */
export type ManagerNotificationPreferencesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * The data needed to update a ManagerNotificationPreferences.
   */
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateInput>
  /**
   * Choose, which ManagerNotificationPreferences to update.
   */
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
}

/**
 * ManagerNotificationPreferences updateMany
 */
export type ManagerNotificationPreferencesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ManagerNotificationPreferences.
   */
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateManyMutationInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateManyInput>
  /**
   * Filter which ManagerNotificationPreferences to update
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * Limit how many ManagerNotificationPreferences to update.
   */
  limit?: number
}

/**
 * ManagerNotificationPreferences updateManyAndReturn
 */
export type ManagerNotificationPreferencesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * The data used to update ManagerNotificationPreferences.
   */
  data: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateManyMutationInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateManyInput>
  /**
   * Filter which ManagerNotificationPreferences to update
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * Limit how many ManagerNotificationPreferences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ManagerNotificationPreferences upsert
 */
export type ManagerNotificationPreferencesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * The filter to search for the ManagerNotificationPreferences to update in case it exists.
   */
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
  /**
   * In case the ManagerNotificationPreferences found by the `where` argument doesn't exist, create a new ManagerNotificationPreferences with this data.
   */
  create: Prisma.XOR<Prisma.ManagerNotificationPreferencesCreateInput, Prisma.ManagerNotificationPreferencesUncheckedCreateInput>
  /**
   * In case the ManagerNotificationPreferences was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManagerNotificationPreferencesUpdateInput, Prisma.ManagerNotificationPreferencesUncheckedUpdateInput>
}

/**
 * ManagerNotificationPreferences delete
 */
export type ManagerNotificationPreferencesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
  /**
   * Filter which ManagerNotificationPreferences to delete.
   */
  where: Prisma.ManagerNotificationPreferencesWhereUniqueInput
}

/**
 * ManagerNotificationPreferences deleteMany
 */
export type ManagerNotificationPreferencesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManagerNotificationPreferences to delete
   */
  where?: Prisma.ManagerNotificationPreferencesWhereInput
  /**
   * Limit how many ManagerNotificationPreferences to delete.
   */
  limit?: number
}

/**
 * ManagerNotificationPreferences without action
 */
export type ManagerNotificationPreferencesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagerNotificationPreferences
   */
  select?: Prisma.ManagerNotificationPreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagerNotificationPreferences
   */
  omit?: Prisma.ManagerNotificationPreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagerNotificationPreferencesInclude<ExtArgs> | null
}
