nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  "@lukemorales/query-key-factory@*":
    peerDependenciesMeta:
      "@tanstack/query-core":
        optional: true
