
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  mobile_phone: 'mobile_phone',
  orders_aist: 'orders_aist',
  orders_aliexpress: 'orders_aliexpress',
  orders_aliexpress_krym: 'orders_aliexpress_krym',
  orders_banki_rf: 'orders_banki_rf',
  orders_call_back: 'orders_call_back',
  orders_call_backDO: 'orders_call_backDO',
  orders_call_backGO: 'orders_call_backGO',
  orders_cart: 'orders_cart',
  orders_commers: 'orders_commers',
  orders_doski: 'orders_doski',
  orders_dostavka_ali: 'orders_dostavka_ali',
  orders_dostavka_rus: 'orders_dostavka_rus',
  orders_fromabroad: 'orders_fromabroad',
  orders_hotline: 'orders_hotline',
  orders_iz_rf: 'orders_iz_rf',
  orders_iz_krim_ldnr: 'orders_iz_krim_ldnr',
  orders_sadovod: 'orders_sadovod',
  orders_temernik: 'orders_temernik',
  zabor_commerc: 'zabor_commerc',
  zabor_gruza: 'zabor_gruza',
  zabor_gruzaDNR: 'zabor_gruzaDNR',
  zabor_gruzaKrym: 'zabor_gruzaKrym',
  zabor_gruzaLNR: 'zabor_gruzaLNR',
  zayvka_form: 'zayvka_form'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Mobile_phoneScalarFieldEnum = {
  id: 'id',
  city: 'city',
  adress: 'adress',
  number: 'number'
} as const

export type Mobile_phoneScalarFieldEnum = (typeof Mobile_phoneScalarFieldEnum)[keyof typeof Mobile_phoneScalarFieldEnum]


export const Orders_aistScalarFieldEnum = {
  id: 'id',
  data: 'data',
  tip_gruza: 'tip_gruza',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  gruz: 'gruz',
  ves: 'ves',
  trek: 'trek',
  platej: 'platej'
} as const

export type Orders_aistScalarFieldEnum = (typeof Orders_aistScalarFieldEnum)[keyof typeof Orders_aistScalarFieldEnum]


export const Orders_aliexpressScalarFieldEnum = {
  id: 'id',
  date: 'date',
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type Orders_aliexpressScalarFieldEnum = (typeof Orders_aliexpressScalarFieldEnum)[keyof typeof Orders_aliexpressScalarFieldEnum]


export const Orders_aliexpress_krymScalarFieldEnum = {
  id: 'id',
  date: 'date',
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type Orders_aliexpress_krymScalarFieldEnum = (typeof Orders_aliexpress_krymScalarFieldEnum)[keyof typeof Orders_aliexpress_krymScalarFieldEnum]


export const Orders_banki_rfScalarFieldEnum = {
  id: 'id',
  date: 'date',
  name: 'name',
  phone: 'phone',
  timechek: 'timechek',
  amount: 'amount',
  metod: 'metod',
  dkarta: 'dkarta',
  nameP: 'nameP',
  phoneP: 'phoneP',
  departament: 'departament'
} as const

export type Orders_banki_rfScalarFieldEnum = (typeof Orders_banki_rfScalarFieldEnum)[keyof typeof Orders_banki_rfScalarFieldEnum]


export const Orders_call_backScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone'
} as const

export type Orders_call_backScalarFieldEnum = (typeof Orders_call_backScalarFieldEnum)[keyof typeof Orders_call_backScalarFieldEnum]


export const Orders_call_backDOScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone'
} as const

export type Orders_call_backDOScalarFieldEnum = (typeof Orders_call_backDOScalarFieldEnum)[keyof typeof Orders_call_backDOScalarFieldEnum]


export const Orders_call_backGOScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone'
} as const

export type Orders_call_backGOScalarFieldEnum = (typeof Orders_call_backGOScalarFieldEnum)[keyof typeof Orders_call_backGOScalarFieldEnum]


export const Orders_cartScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  birth: 'birth',
  pass: 'pass',
  mail: 'mail',
  phone: 'phone',
  departament: 'departament'
} as const

export type Orders_cartScalarFieldEnum = (typeof Orders_cartScalarFieldEnum)[keyof typeof Orders_cartScalarFieldEnum]


export const Orders_commersScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  links: 'links',
  amount: 'amount',
  weight: 'weight'
} as const

export type Orders_commersScalarFieldEnum = (typeof Orders_commersScalarFieldEnum)[keyof typeof Orders_commersScalarFieldEnum]


export const Orders_doskiScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  TK: 'TK',
  trek: 'trek',
  opisanie: 'opisanie',
  nomer_karti: 'nomer_karti',
  FIO_karti: 'FIO_karti',
  summa: 'summa',
  name_poluch: 'name_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament'
} as const

export type Orders_doskiScalarFieldEnum = (typeof Orders_doskiScalarFieldEnum)[keyof typeof Orders_doskiScalarFieldEnum]


export const Orders_dostavka_aliScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  razmer: 'razmer',
  color: 'color',
  colvo: 'colvo',
  amount: 'amount'
} as const

export type Orders_dostavka_aliScalarFieldEnum = (typeof Orders_dostavka_aliScalarFieldEnum)[keyof typeof Orders_dostavka_aliScalarFieldEnum]


export const Orders_dostavka_rusScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type Orders_dostavka_rusScalarFieldEnum = (typeof Orders_dostavka_rusScalarFieldEnum)[keyof typeof Orders_dostavka_rusScalarFieldEnum]


export const Orders_fromabroadScalarFieldEnum = {
  id: 'id',
  date: 'date',
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type Orders_fromabroadScalarFieldEnum = (typeof Orders_fromabroadScalarFieldEnum)[keyof typeof Orders_fromabroadScalarFieldEnum]


export const Orders_hotlineScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  mail: 'mail',
  phone: 'phone',
  complaint: 'complaint'
} as const

export type Orders_hotlineScalarFieldEnum = (typeof Orders_hotlineScalarFieldEnum)[keyof typeof Orders_hotlineScalarFieldEnum]


export const Orders_iz_rfScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type Orders_iz_rfScalarFieldEnum = (typeof Orders_iz_rfScalarFieldEnum)[keyof typeof Orders_iz_rfScalarFieldEnum]


export const Orders_iz_krim_ldnrScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  trek: 'trek',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type Orders_iz_krim_ldnrScalarFieldEnum = (typeof Orders_iz_krim_ldnrScalarFieldEnum)[keyof typeof Orders_iz_krim_ldnrScalarFieldEnum]


export const Orders_sadovodScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type Orders_sadovodScalarFieldEnum = (typeof Orders_sadovodScalarFieldEnum)[keyof typeof Orders_sadovodScalarFieldEnum]


export const Orders_temernikScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type Orders_temernikScalarFieldEnum = (typeof Orders_temernikScalarFieldEnum)[keyof typeof Orders_temernikScalarFieldEnum]


export const Zabor_commercScalarFieldEnum = {
  id: 'id',
  data: 'data',
  trek: 'trek',
  tkadress: 'tkadress',
  name: 'name',
  naznachenie: 'naznachenie',
  colvo: 'colvo',
  amount: 'amount',
  kuda: 'kuda',
  tel: 'tel',
  mail: 'mail'
} as const

export type Zabor_commercScalarFieldEnum = (typeof Zabor_commercScalarFieldEnum)[keyof typeof Zabor_commercScalarFieldEnum]


export const Zabor_gruzaScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type Zabor_gruzaScalarFieldEnum = (typeof Zabor_gruzaScalarFieldEnum)[keyof typeof Zabor_gruzaScalarFieldEnum]


export const Zabor_gruzaDNRScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type Zabor_gruzaDNRScalarFieldEnum = (typeof Zabor_gruzaDNRScalarFieldEnum)[keyof typeof Zabor_gruzaDNRScalarFieldEnum]


export const Zabor_gruzaKrymScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type Zabor_gruzaKrymScalarFieldEnum = (typeof Zabor_gruzaKrymScalarFieldEnum)[keyof typeof Zabor_gruzaKrymScalarFieldEnum]


export const Zabor_gruzaLNRScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type Zabor_gruzaLNRScalarFieldEnum = (typeof Zabor_gruzaLNRScalarFieldEnum)[keyof typeof Zabor_gruzaLNRScalarFieldEnum]


export const Zayvka_formScalarFieldEnum = {
  id: 'id',
  data: 'data',
  name: 'name',
  mail: 'mail',
  phone: 'phone'
} as const

export type Zayvka_formScalarFieldEnum = (typeof Zayvka_formScalarFieldEnum)[keyof typeof Zayvka_formScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const mobile_phoneOrderByRelevanceFieldEnum = {
  city: 'city',
  adress: 'adress',
  number: 'number'
} as const

export type mobile_phoneOrderByRelevanceFieldEnum = (typeof mobile_phoneOrderByRelevanceFieldEnum)[keyof typeof mobile_phoneOrderByRelevanceFieldEnum]


export const orders_aistOrderByRelevanceFieldEnum = {
  tip_gruza: 'tip_gruza',
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  gruz: 'gruz',
  ves: 'ves',
  trek: 'trek',
  platej: 'platej'
} as const

export type orders_aistOrderByRelevanceFieldEnum = (typeof orders_aistOrderByRelevanceFieldEnum)[keyof typeof orders_aistOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const orders_aliexpressOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type orders_aliexpressOrderByRelevanceFieldEnum = (typeof orders_aliexpressOrderByRelevanceFieldEnum)[keyof typeof orders_aliexpressOrderByRelevanceFieldEnum]


export const orders_aliexpress_krymOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type orders_aliexpress_krymOrderByRelevanceFieldEnum = (typeof orders_aliexpress_krymOrderByRelevanceFieldEnum)[keyof typeof orders_aliexpress_krymOrderByRelevanceFieldEnum]


export const orders_banki_rfOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  timechek: 'timechek',
  amount: 'amount',
  metod: 'metod',
  dkarta: 'dkarta',
  nameP: 'nameP',
  phoneP: 'phoneP',
  departament: 'departament'
} as const

export type orders_banki_rfOrderByRelevanceFieldEnum = (typeof orders_banki_rfOrderByRelevanceFieldEnum)[keyof typeof orders_banki_rfOrderByRelevanceFieldEnum]


export const orders_call_backOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone'
} as const

export type orders_call_backOrderByRelevanceFieldEnum = (typeof orders_call_backOrderByRelevanceFieldEnum)[keyof typeof orders_call_backOrderByRelevanceFieldEnum]


export const orders_call_backDOOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone'
} as const

export type orders_call_backDOOrderByRelevanceFieldEnum = (typeof orders_call_backDOOrderByRelevanceFieldEnum)[keyof typeof orders_call_backDOOrderByRelevanceFieldEnum]


export const orders_call_backGOOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone'
} as const

export type orders_call_backGOOrderByRelevanceFieldEnum = (typeof orders_call_backGOOrderByRelevanceFieldEnum)[keyof typeof orders_call_backGOOrderByRelevanceFieldEnum]


export const orders_cartOrderByRelevanceFieldEnum = {
  name: 'name',
  birth: 'birth',
  pass: 'pass',
  mail: 'mail',
  phone: 'phone',
  departament: 'departament'
} as const

export type orders_cartOrderByRelevanceFieldEnum = (typeof orders_cartOrderByRelevanceFieldEnum)[keyof typeof orders_cartOrderByRelevanceFieldEnum]


export const orders_commersOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  links: 'links',
  amount: 'amount',
  weight: 'weight'
} as const

export type orders_commersOrderByRelevanceFieldEnum = (typeof orders_commersOrderByRelevanceFieldEnum)[keyof typeof orders_commersOrderByRelevanceFieldEnum]


export const orders_doskiOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  TK: 'TK',
  trek: 'trek',
  opisanie: 'opisanie',
  nomer_karti: 'nomer_karti',
  FIO_karti: 'FIO_karti',
  summa: 'summa',
  name_poluch: 'name_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament'
} as const

export type orders_doskiOrderByRelevanceFieldEnum = (typeof orders_doskiOrderByRelevanceFieldEnum)[keyof typeof orders_doskiOrderByRelevanceFieldEnum]


export const orders_dostavka_aliOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  razmer: 'razmer',
  color: 'color',
  colvo: 'colvo',
  amount: 'amount'
} as const

export type orders_dostavka_aliOrderByRelevanceFieldEnum = (typeof orders_dostavka_aliOrderByRelevanceFieldEnum)[keyof typeof orders_dostavka_aliOrderByRelevanceFieldEnum]


export const orders_dostavka_rusOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type orders_dostavka_rusOrderByRelevanceFieldEnum = (typeof orders_dostavka_rusOrderByRelevanceFieldEnum)[keyof typeof orders_dostavka_rusOrderByRelevanceFieldEnum]


export const orders_fromabroadOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type orders_fromabroadOrderByRelevanceFieldEnum = (typeof orders_fromabroadOrderByRelevanceFieldEnum)[keyof typeof orders_fromabroadOrderByRelevanceFieldEnum]


export const orders_hotlineOrderByRelevanceFieldEnum = {
  name: 'name',
  mail: 'mail',
  phone: 'phone',
  complaint: 'complaint'
} as const

export type orders_hotlineOrderByRelevanceFieldEnum = (typeof orders_hotlineOrderByRelevanceFieldEnum)[keyof typeof orders_hotlineOrderByRelevanceFieldEnum]


export const orders_iz_rfOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  links: 'links',
  amount: 'amount',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  track_number: 'track_number',
  mail: 'mail',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type orders_iz_rfOrderByRelevanceFieldEnum = (typeof orders_iz_rfOrderByRelevanceFieldEnum)[keyof typeof orders_iz_rfOrderByRelevanceFieldEnum]


export const orders_iz_krim_ldnrOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  passport: 'passport',
  vidan: 'vidan',
  kogda: 'kogda',
  pasldnr: 'pasldnr',
  departament: 'departament',
  name_Otpravitelya: 'name_Otpravitelya',
  TK: 'TK',
  trek: 'trek',
  citi_otprav: 'citi_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  opisanie: 'opisanie',
  VIP: 'VIP'
} as const

export type orders_iz_krim_ldnrOrderByRelevanceFieldEnum = (typeof orders_iz_krim_ldnrOrderByRelevanceFieldEnum)[keyof typeof orders_iz_krim_ldnrOrderByRelevanceFieldEnum]


export const orders_sadovodOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type orders_sadovodOrderByRelevanceFieldEnum = (typeof orders_sadovodOrderByRelevanceFieldEnum)[keyof typeof orders_sadovodOrderByRelevanceFieldEnum]


export const orders_temernikOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  mail: 'mail',
  departament: 'departament',
  links: 'links',
  opisanie: 'opisanie',
  amount: 'amount'
} as const

export type orders_temernikOrderByRelevanceFieldEnum = (typeof orders_temernikOrderByRelevanceFieldEnum)[keyof typeof orders_temernikOrderByRelevanceFieldEnum]


export const zabor_commercOrderByRelevanceFieldEnum = {
  trek: 'trek',
  tkadress: 'tkadress',
  name: 'name',
  naznachenie: 'naznachenie',
  colvo: 'colvo',
  amount: 'amount',
  kuda: 'kuda',
  tel: 'tel',
  mail: 'mail'
} as const

export type zabor_commercOrderByRelevanceFieldEnum = (typeof zabor_commercOrderByRelevanceFieldEnum)[keyof typeof zabor_commercOrderByRelevanceFieldEnum]


export const zabor_gruzaOrderByRelevanceFieldEnum = {
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type zabor_gruzaOrderByRelevanceFieldEnum = (typeof zabor_gruzaOrderByRelevanceFieldEnum)[keyof typeof zabor_gruzaOrderByRelevanceFieldEnum]


export const zabor_gruzaDNROrderByRelevanceFieldEnum = {
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type zabor_gruzaDNROrderByRelevanceFieldEnum = (typeof zabor_gruzaDNROrderByRelevanceFieldEnum)[keyof typeof zabor_gruzaDNROrderByRelevanceFieldEnum]


export const zabor_gruzaKrymOrderByRelevanceFieldEnum = {
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type zabor_gruzaKrymOrderByRelevanceFieldEnum = (typeof zabor_gruzaKrymOrderByRelevanceFieldEnum)[keyof typeof zabor_gruzaKrymOrderByRelevanceFieldEnum]


export const zabor_gruzaLNROrderByRelevanceFieldEnum = {
  name_Otpravitelya: 'name_Otpravitelya',
  town_otprav: 'town_otprav',
  citi_otprav: 'citi_otprav',
  time_otprav: 'time_otprav',
  phone_otprav: 'phone_otprav',
  kto_oplachivaet: 'kto_oplachivaet',
  kol_vo: 'kol_vo',
  ves: 'ves',
  obyem: 'obyem',
  stoimost: 'stoimost',
  ves_gruza: 'ves_gruza',
  name_gruz: 'name_gruz',
  gabariti: 'gabariti',
  khrupkiy_gruz: 'khrupkiy_gruz',
  name_otprav: 'name_otprav',
  citi_poluch: 'citi_poluch',
  phone_poluch: 'phone_poluch',
  departament: 'departament',
  name_zakaz: 'name_zakaz',
  mail: 'mail',
  phone_zakaz: 'phone_zakaz'
} as const

export type zabor_gruzaLNROrderByRelevanceFieldEnum = (typeof zabor_gruzaLNROrderByRelevanceFieldEnum)[keyof typeof zabor_gruzaLNROrderByRelevanceFieldEnum]


export const zayvka_formOrderByRelevanceFieldEnum = {
  name: 'name',
  mail: 'mail',
  phone: 'phone'
} as const

export type zayvka_formOrderByRelevanceFieldEnum = (typeof zayvka_formOrderByRelevanceFieldEnum)[keyof typeof zayvka_formOrderByRelevanceFieldEnum]

