
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model TelegramUser
 * Base model for any Telegram user (managers, clients, etc.)
 */
export type TelegramUser = Prisma.TelegramUserModel
/**
 * Model Manager
 * Manager profile - extends TelegramUser
 * These are staff members who receive notifications
 */
export type Manager = Prisma.ManagerModel
/**
 * Model Client
 * Client profile - extends TelegramUser
 * These are your customers who use the service
 */
export type Client = Prisma.ClientModel
/**
 * Model NotificationType
 * 
 */
export type NotificationType = Prisma.NotificationTypeModel
/**
 * Model ManagerNotificationPreferences
 * 
 */
export type ManagerNotificationPreferences = Prisma.ManagerNotificationPreferencesModel
/**
 * Model NotificationLog
 * 
 */
export type NotificationLog = Prisma.NotificationLogModel
