
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/TelegramUser.ts'
export type * from './models/Manager.ts'
export type * from './models/Client.ts'
export type * from './models/NotificationType.ts'
export type * from './models/ManagerNotificationPreferences.ts'
export type * from './models/NotificationLog.ts'
export type * from './commonInputTypes.ts'