
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_cart` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_cart
 * 
 */
export type orders_cartModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_cartPayload>

export type AggregateOrders_cart = {
  _count: Orders_cartCountAggregateOutputType | null
  _avg: Orders_cartAvgAggregateOutputType | null
  _sum: Orders_cartSumAggregateOutputType | null
  _min: Orders_cartMinAggregateOutputType | null
  _max: Orders_cartMaxAggregateOutputType | null
}

export type Orders_cartAvgAggregateOutputType = {
  id: number | null
}

export type Orders_cartSumAggregateOutputType = {
  id: number | null
}

export type Orders_cartMinAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  birth: string | null
  pass: string | null
  mail: string | null
  phone: string | null
  departament: string | null
}

export type Orders_cartMaxAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  birth: string | null
  pass: string | null
  mail: string | null
  phone: string | null
  departament: string | null
}

export type Orders_cartCountAggregateOutputType = {
  id: number
  data: number
  name: number
  birth: number
  pass: number
  mail: number
  phone: number
  departament: number
  _all: number
}


export type Orders_cartAvgAggregateInputType = {
  id?: true
}

export type Orders_cartSumAggregateInputType = {
  id?: true
}

export type Orders_cartMinAggregateInputType = {
  id?: true
  data?: true
  name?: true
  birth?: true
  pass?: true
  mail?: true
  phone?: true
  departament?: true
}

export type Orders_cartMaxAggregateInputType = {
  id?: true
  data?: true
  name?: true
  birth?: true
  pass?: true
  mail?: true
  phone?: true
  departament?: true
}

export type Orders_cartCountAggregateInputType = {
  id?: true
  data?: true
  name?: true
  birth?: true
  pass?: true
  mail?: true
  phone?: true
  departament?: true
  _all?: true
}

export type Orders_cartAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_cart to aggregate.
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_carts to fetch.
   */
  orderBy?: Prisma.orders_cartOrderByWithRelationInput | Prisma.orders_cartOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_cartWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_carts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_carts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_carts
  **/
  _count?: true | Orders_cartCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_cartAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_cartSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_cartMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_cartMaxAggregateInputType
}

export type GetOrders_cartAggregateType<T extends Orders_cartAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_cart]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_cart[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_cart[P]>
}




export type orders_cartGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_cartWhereInput
  orderBy?: Prisma.orders_cartOrderByWithAggregationInput | Prisma.orders_cartOrderByWithAggregationInput[]
  by: Prisma.Orders_cartScalarFieldEnum[] | Prisma.Orders_cartScalarFieldEnum
  having?: Prisma.orders_cartScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_cartCountAggregateInputType | true
  _avg?: Orders_cartAvgAggregateInputType
  _sum?: Orders_cartSumAggregateInputType
  _min?: Orders_cartMinAggregateInputType
  _max?: Orders_cartMaxAggregateInputType
}

export type Orders_cartGroupByOutputType = {
  id: number
  data: Date
  name: string
  birth: string
  pass: string
  mail: string
  phone: string
  departament: string
  _count: Orders_cartCountAggregateOutputType | null
  _avg: Orders_cartAvgAggregateOutputType | null
  _sum: Orders_cartSumAggregateOutputType | null
  _min: Orders_cartMinAggregateOutputType | null
  _max: Orders_cartMaxAggregateOutputType | null
}

export type GetOrders_cartGroupByPayload<T extends orders_cartGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_cartGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_cartGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_cartGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_cartGroupByOutputType[P]>
      }
    >
  >



export type orders_cartWhereInput = {
  AND?: Prisma.orders_cartWhereInput | Prisma.orders_cartWhereInput[]
  OR?: Prisma.orders_cartWhereInput[]
  NOT?: Prisma.orders_cartWhereInput | Prisma.orders_cartWhereInput[]
  id?: Prisma.IntFilter<"orders_cart"> | number
  data?: Prisma.DateTimeFilter<"orders_cart"> | Date | string
  name?: Prisma.StringFilter<"orders_cart"> | string
  birth?: Prisma.StringFilter<"orders_cart"> | string
  pass?: Prisma.StringFilter<"orders_cart"> | string
  mail?: Prisma.StringFilter<"orders_cart"> | string
  phone?: Prisma.StringFilter<"orders_cart"> | string
  departament?: Prisma.StringFilter<"orders_cart"> | string
}

export type orders_cartOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  pass?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  _relevance?: Prisma.orders_cartOrderByRelevanceInput
}

export type orders_cartWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_cartWhereInput | Prisma.orders_cartWhereInput[]
  OR?: Prisma.orders_cartWhereInput[]
  NOT?: Prisma.orders_cartWhereInput | Prisma.orders_cartWhereInput[]
  data?: Prisma.DateTimeFilter<"orders_cart"> | Date | string
  name?: Prisma.StringFilter<"orders_cart"> | string
  birth?: Prisma.StringFilter<"orders_cart"> | string
  pass?: Prisma.StringFilter<"orders_cart"> | string
  mail?: Prisma.StringFilter<"orders_cart"> | string
  phone?: Prisma.StringFilter<"orders_cart"> | string
  departament?: Prisma.StringFilter<"orders_cart"> | string
}, "id">

export type orders_cartOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  pass?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  _count?: Prisma.orders_cartCountOrderByAggregateInput
  _avg?: Prisma.orders_cartAvgOrderByAggregateInput
  _max?: Prisma.orders_cartMaxOrderByAggregateInput
  _min?: Prisma.orders_cartMinOrderByAggregateInput
  _sum?: Prisma.orders_cartSumOrderByAggregateInput
}

export type orders_cartScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_cartScalarWhereWithAggregatesInput | Prisma.orders_cartScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_cartScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_cartScalarWhereWithAggregatesInput | Prisma.orders_cartScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_cart"> | number
  data?: Prisma.DateTimeWithAggregatesFilter<"orders_cart"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
  birth?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
  pass?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
  mail?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_cart"> | string
}

export type orders_cartCreateInput = {
  data?: Date | string
  name: string
  birth: string
  pass: string
  mail: string
  phone: string
  departament: string
}

export type orders_cartUncheckedCreateInput = {
  id?: number
  data?: Date | string
  name: string
  birth: string
  pass: string
  mail: string
  phone: string
  departament: string
}

export type orders_cartUpdateInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.StringFieldUpdateOperationsInput | string
  pass?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_cartUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.StringFieldUpdateOperationsInput | string
  pass?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_cartCreateManyInput = {
  id?: number
  data?: Date | string
  name: string
  birth: string
  pass: string
  mail: string
  phone: string
  departament: string
}

export type orders_cartUpdateManyMutationInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.StringFieldUpdateOperationsInput | string
  pass?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_cartUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.StringFieldUpdateOperationsInput | string
  pass?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_cartOrderByRelevanceInput = {
  fields: Prisma.orders_cartOrderByRelevanceFieldEnum | Prisma.orders_cartOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_cartCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  pass?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_cartAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_cartMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  pass?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_cartMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  pass?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_cartSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_cartSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  name?: boolean
  birth?: boolean
  pass?: boolean
  mail?: boolean
  phone?: boolean
  departament?: boolean
}, ExtArgs["result"]["orders_cart"]>



export type orders_cartSelectScalar = {
  id?: boolean
  data?: boolean
  name?: boolean
  birth?: boolean
  pass?: boolean
  mail?: boolean
  phone?: boolean
  departament?: boolean
}

export type orders_cartOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "name" | "birth" | "pass" | "mail" | "phone" | "departament", ExtArgs["result"]["orders_cart"]>

export type $orders_cartPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_cart"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    data: Date
    name: string
    birth: string
    pass: string
    mail: string
    phone: string
    departament: string
  }, ExtArgs["result"]["orders_cart"]>
  composites: {}
}

export type orders_cartGetPayload<S extends boolean | null | undefined | orders_cartDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_cartPayload, S>

export type orders_cartCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_cartFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_cartCountAggregateInputType | true
  }

export interface orders_cartDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_cart'], meta: { name: 'orders_cart' } }
  /**
   * Find zero or one Orders_cart that matches the filter.
   * @param {orders_cartFindUniqueArgs} args - Arguments to find a Orders_cart
   * @example
   * // Get one Orders_cart
   * const orders_cart = await prisma.orders_cart.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_cartFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_cartFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_cart that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_cartFindUniqueOrThrowArgs} args - Arguments to find a Orders_cart
   * @example
   * // Get one Orders_cart
   * const orders_cart = await prisma.orders_cart.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_cartFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_cartFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_cart that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartFindFirstArgs} args - Arguments to find a Orders_cart
   * @example
   * // Get one Orders_cart
   * const orders_cart = await prisma.orders_cart.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_cartFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_cartFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_cart that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartFindFirstOrThrowArgs} args - Arguments to find a Orders_cart
   * @example
   * // Get one Orders_cart
   * const orders_cart = await prisma.orders_cart.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_cartFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_cartFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_carts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_carts
   * const orders_carts = await prisma.orders_cart.findMany()
   * 
   * // Get first 10 Orders_carts
   * const orders_carts = await prisma.orders_cart.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_cartWithIdOnly = await prisma.orders_cart.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_cartFindManyArgs>(args?: Prisma.SelectSubset<T, orders_cartFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_cart.
   * @param {orders_cartCreateArgs} args - Arguments to create a Orders_cart.
   * @example
   * // Create one Orders_cart
   * const Orders_cart = await prisma.orders_cart.create({
   *   data: {
   *     // ... data to create a Orders_cart
   *   }
   * })
   * 
   */
  create<T extends orders_cartCreateArgs>(args: Prisma.SelectSubset<T, orders_cartCreateArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_carts.
   * @param {orders_cartCreateManyArgs} args - Arguments to create many Orders_carts.
   * @example
   * // Create many Orders_carts
   * const orders_cart = await prisma.orders_cart.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_cartCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_cartCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_cart.
   * @param {orders_cartDeleteArgs} args - Arguments to delete one Orders_cart.
   * @example
   * // Delete one Orders_cart
   * const Orders_cart = await prisma.orders_cart.delete({
   *   where: {
   *     // ... filter to delete one Orders_cart
   *   }
   * })
   * 
   */
  delete<T extends orders_cartDeleteArgs>(args: Prisma.SelectSubset<T, orders_cartDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_cart.
   * @param {orders_cartUpdateArgs} args - Arguments to update one Orders_cart.
   * @example
   * // Update one Orders_cart
   * const orders_cart = await prisma.orders_cart.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_cartUpdateArgs>(args: Prisma.SelectSubset<T, orders_cartUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_carts.
   * @param {orders_cartDeleteManyArgs} args - Arguments to filter Orders_carts to delete.
   * @example
   * // Delete a few Orders_carts
   * const { count } = await prisma.orders_cart.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_cartDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_cartDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_carts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_carts
   * const orders_cart = await prisma.orders_cart.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_cartUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_cartUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_cart.
   * @param {orders_cartUpsertArgs} args - Arguments to update or create a Orders_cart.
   * @example
   * // Update or create a Orders_cart
   * const orders_cart = await prisma.orders_cart.upsert({
   *   create: {
   *     // ... data to create a Orders_cart
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_cart we want to update
   *   }
   * })
   */
  upsert<T extends orders_cartUpsertArgs>(args: Prisma.SelectSubset<T, orders_cartUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_cartClient<runtime.Types.Result.GetResult<Prisma.$orders_cartPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_carts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartCountArgs} args - Arguments to filter Orders_carts to count.
   * @example
   * // Count the number of Orders_carts
   * const count = await prisma.orders_cart.count({
   *   where: {
   *     // ... the filter for the Orders_carts we want to count
   *   }
   * })
  **/
  count<T extends orders_cartCountArgs>(
    args?: Prisma.Subset<T, orders_cartCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_cartCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_cart.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_cartAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_cartAggregateArgs>(args: Prisma.Subset<T, Orders_cartAggregateArgs>): Prisma.PrismaPromise<GetOrders_cartAggregateType<T>>

  /**
   * Group by Orders_cart.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_cartGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_cartGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_cartGroupByArgs['orderBy'] }
      : { orderBy?: orders_cartGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_cartGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_cartGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_cart model
 */
readonly fields: orders_cartFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_cart.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_cartClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_cart model
 */
export interface orders_cartFieldRefs {
  readonly id: Prisma.FieldRef<"orders_cart", 'Int'>
  readonly data: Prisma.FieldRef<"orders_cart", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_cart", 'String'>
  readonly birth: Prisma.FieldRef<"orders_cart", 'String'>
  readonly pass: Prisma.FieldRef<"orders_cart", 'String'>
  readonly mail: Prisma.FieldRef<"orders_cart", 'String'>
  readonly phone: Prisma.FieldRef<"orders_cart", 'String'>
  readonly departament: Prisma.FieldRef<"orders_cart", 'String'>
}
    

// Custom InputTypes
/**
 * orders_cart findUnique
 */
export type orders_cartFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter, which orders_cart to fetch.
   */
  where: Prisma.orders_cartWhereUniqueInput
}

/**
 * orders_cart findUniqueOrThrow
 */
export type orders_cartFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter, which orders_cart to fetch.
   */
  where: Prisma.orders_cartWhereUniqueInput
}

/**
 * orders_cart findFirst
 */
export type orders_cartFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter, which orders_cart to fetch.
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_carts to fetch.
   */
  orderBy?: Prisma.orders_cartOrderByWithRelationInput | Prisma.orders_cartOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_carts.
   */
  cursor?: Prisma.orders_cartWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_carts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_carts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_carts.
   */
  distinct?: Prisma.Orders_cartScalarFieldEnum | Prisma.Orders_cartScalarFieldEnum[]
}

/**
 * orders_cart findFirstOrThrow
 */
export type orders_cartFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter, which orders_cart to fetch.
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_carts to fetch.
   */
  orderBy?: Prisma.orders_cartOrderByWithRelationInput | Prisma.orders_cartOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_carts.
   */
  cursor?: Prisma.orders_cartWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_carts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_carts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_carts.
   */
  distinct?: Prisma.Orders_cartScalarFieldEnum | Prisma.Orders_cartScalarFieldEnum[]
}

/**
 * orders_cart findMany
 */
export type orders_cartFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter, which orders_carts to fetch.
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_carts to fetch.
   */
  orderBy?: Prisma.orders_cartOrderByWithRelationInput | Prisma.orders_cartOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_carts.
   */
  cursor?: Prisma.orders_cartWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_carts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_carts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_carts.
   */
  distinct?: Prisma.Orders_cartScalarFieldEnum | Prisma.Orders_cartScalarFieldEnum[]
}

/**
 * orders_cart create
 */
export type orders_cartCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_cart.
   */
  data: Prisma.XOR<Prisma.orders_cartCreateInput, Prisma.orders_cartUncheckedCreateInput>
}

/**
 * orders_cart createMany
 */
export type orders_cartCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_carts.
   */
  data: Prisma.orders_cartCreateManyInput | Prisma.orders_cartCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_cart update
 */
export type orders_cartUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_cart.
   */
  data: Prisma.XOR<Prisma.orders_cartUpdateInput, Prisma.orders_cartUncheckedUpdateInput>
  /**
   * Choose, which orders_cart to update.
   */
  where: Prisma.orders_cartWhereUniqueInput
}

/**
 * orders_cart updateMany
 */
export type orders_cartUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_carts.
   */
  data: Prisma.XOR<Prisma.orders_cartUpdateManyMutationInput, Prisma.orders_cartUncheckedUpdateManyInput>
  /**
   * Filter which orders_carts to update
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * Limit how many orders_carts to update.
   */
  limit?: number
}

/**
 * orders_cart upsert
 */
export type orders_cartUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_cart to update in case it exists.
   */
  where: Prisma.orders_cartWhereUniqueInput
  /**
   * In case the orders_cart found by the `where` argument doesn't exist, create a new orders_cart with this data.
   */
  create: Prisma.XOR<Prisma.orders_cartCreateInput, Prisma.orders_cartUncheckedCreateInput>
  /**
   * In case the orders_cart was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_cartUpdateInput, Prisma.orders_cartUncheckedUpdateInput>
}

/**
 * orders_cart delete
 */
export type orders_cartDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
  /**
   * Filter which orders_cart to delete.
   */
  where: Prisma.orders_cartWhereUniqueInput
}

/**
 * orders_cart deleteMany
 */
export type orders_cartDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_carts to delete
   */
  where?: Prisma.orders_cartWhereInput
  /**
   * Limit how many orders_carts to delete.
   */
  limit?: number
}

/**
 * orders_cart without action
 */
export type orders_cartDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_cart
   */
  select?: Prisma.orders_cartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_cart
   */
  omit?: Prisma.orders_cartOmit<ExtArgs> | null
}
