
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_banki_rf` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_banki_rf
 * 
 */
export type orders_banki_rfModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_banki_rfPayload>

export type AggregateOrders_banki_rf = {
  _count: Orders_banki_rfCountAggregateOutputType | null
  _avg: Orders_banki_rfAvgAggregateOutputType | null
  _sum: Orders_banki_rfSumAggregateOutputType | null
  _min: Orders_banki_rfMinAggregateOutputType | null
  _max: Orders_banki_rfMaxAggregateOutputType | null
}

export type Orders_banki_rfAvgAggregateOutputType = {
  id: number | null
}

export type Orders_banki_rfSumAggregateOutputType = {
  id: number | null
}

export type Orders_banki_rfMinAggregateOutputType = {
  id: number | null
  date: Date | null
  name: string | null
  phone: string | null
  timechek: string | null
  amount: string | null
  metod: string | null
  dkarta: string | null
  nameP: string | null
  phoneP: string | null
  departament: string | null
}

export type Orders_banki_rfMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  name: string | null
  phone: string | null
  timechek: string | null
  amount: string | null
  metod: string | null
  dkarta: string | null
  nameP: string | null
  phoneP: string | null
  departament: string | null
}

export type Orders_banki_rfCountAggregateOutputType = {
  id: number
  date: number
  name: number
  phone: number
  timechek: number
  amount: number
  metod: number
  dkarta: number
  nameP: number
  phoneP: number
  departament: number
  _all: number
}


export type Orders_banki_rfAvgAggregateInputType = {
  id?: true
}

export type Orders_banki_rfSumAggregateInputType = {
  id?: true
}

export type Orders_banki_rfMinAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  timechek?: true
  amount?: true
  metod?: true
  dkarta?: true
  nameP?: true
  phoneP?: true
  departament?: true
}

export type Orders_banki_rfMaxAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  timechek?: true
  amount?: true
  metod?: true
  dkarta?: true
  nameP?: true
  phoneP?: true
  departament?: true
}

export type Orders_banki_rfCountAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  timechek?: true
  amount?: true
  metod?: true
  dkarta?: true
  nameP?: true
  phoneP?: true
  departament?: true
  _all?: true
}

export type Orders_banki_rfAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_banki_rf to aggregate.
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_banki_rfs to fetch.
   */
  orderBy?: Prisma.orders_banki_rfOrderByWithRelationInput | Prisma.orders_banki_rfOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_banki_rfWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_banki_rfs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_banki_rfs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_banki_rfs
  **/
  _count?: true | Orders_banki_rfCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_banki_rfAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_banki_rfSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_banki_rfMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_banki_rfMaxAggregateInputType
}

export type GetOrders_banki_rfAggregateType<T extends Orders_banki_rfAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_banki_rf]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_banki_rf[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_banki_rf[P]>
}




export type orders_banki_rfGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_banki_rfWhereInput
  orderBy?: Prisma.orders_banki_rfOrderByWithAggregationInput | Prisma.orders_banki_rfOrderByWithAggregationInput[]
  by: Prisma.Orders_banki_rfScalarFieldEnum[] | Prisma.Orders_banki_rfScalarFieldEnum
  having?: Prisma.orders_banki_rfScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_banki_rfCountAggregateInputType | true
  _avg?: Orders_banki_rfAvgAggregateInputType
  _sum?: Orders_banki_rfSumAggregateInputType
  _min?: Orders_banki_rfMinAggregateInputType
  _max?: Orders_banki_rfMaxAggregateInputType
}

export type Orders_banki_rfGroupByOutputType = {
  id: number
  date: Date
  name: string
  phone: string
  timechek: string
  amount: string
  metod: string
  dkarta: string
  nameP: string
  phoneP: string
  departament: string
  _count: Orders_banki_rfCountAggregateOutputType | null
  _avg: Orders_banki_rfAvgAggregateOutputType | null
  _sum: Orders_banki_rfSumAggregateOutputType | null
  _min: Orders_banki_rfMinAggregateOutputType | null
  _max: Orders_banki_rfMaxAggregateOutputType | null
}

export type GetOrders_banki_rfGroupByPayload<T extends orders_banki_rfGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_banki_rfGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_banki_rfGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_banki_rfGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_banki_rfGroupByOutputType[P]>
      }
    >
  >



export type orders_banki_rfWhereInput = {
  AND?: Prisma.orders_banki_rfWhereInput | Prisma.orders_banki_rfWhereInput[]
  OR?: Prisma.orders_banki_rfWhereInput[]
  NOT?: Prisma.orders_banki_rfWhereInput | Prisma.orders_banki_rfWhereInput[]
  id?: Prisma.IntFilter<"orders_banki_rf"> | number
  date?: Prisma.DateTimeFilter<"orders_banki_rf"> | Date | string
  name?: Prisma.StringFilter<"orders_banki_rf"> | string
  phone?: Prisma.StringFilter<"orders_banki_rf"> | string
  timechek?: Prisma.StringFilter<"orders_banki_rf"> | string
  amount?: Prisma.StringFilter<"orders_banki_rf"> | string
  metod?: Prisma.StringFilter<"orders_banki_rf"> | string
  dkarta?: Prisma.StringFilter<"orders_banki_rf"> | string
  nameP?: Prisma.StringFilter<"orders_banki_rf"> | string
  phoneP?: Prisma.StringFilter<"orders_banki_rf"> | string
  departament?: Prisma.StringFilter<"orders_banki_rf"> | string
}

export type orders_banki_rfOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  timechek?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  metod?: Prisma.SortOrder
  dkarta?: Prisma.SortOrder
  nameP?: Prisma.SortOrder
  phoneP?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  _relevance?: Prisma.orders_banki_rfOrderByRelevanceInput
}

export type orders_banki_rfWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_banki_rfWhereInput | Prisma.orders_banki_rfWhereInput[]
  OR?: Prisma.orders_banki_rfWhereInput[]
  NOT?: Prisma.orders_banki_rfWhereInput | Prisma.orders_banki_rfWhereInput[]
  date?: Prisma.DateTimeFilter<"orders_banki_rf"> | Date | string
  name?: Prisma.StringFilter<"orders_banki_rf"> | string
  phone?: Prisma.StringFilter<"orders_banki_rf"> | string
  timechek?: Prisma.StringFilter<"orders_banki_rf"> | string
  amount?: Prisma.StringFilter<"orders_banki_rf"> | string
  metod?: Prisma.StringFilter<"orders_banki_rf"> | string
  dkarta?: Prisma.StringFilter<"orders_banki_rf"> | string
  nameP?: Prisma.StringFilter<"orders_banki_rf"> | string
  phoneP?: Prisma.StringFilter<"orders_banki_rf"> | string
  departament?: Prisma.StringFilter<"orders_banki_rf"> | string
}, "id">

export type orders_banki_rfOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  timechek?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  metod?: Prisma.SortOrder
  dkarta?: Prisma.SortOrder
  nameP?: Prisma.SortOrder
  phoneP?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  _count?: Prisma.orders_banki_rfCountOrderByAggregateInput
  _avg?: Prisma.orders_banki_rfAvgOrderByAggregateInput
  _max?: Prisma.orders_banki_rfMaxOrderByAggregateInput
  _min?: Prisma.orders_banki_rfMinOrderByAggregateInput
  _sum?: Prisma.orders_banki_rfSumOrderByAggregateInput
}

export type orders_banki_rfScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_banki_rfScalarWhereWithAggregatesInput | Prisma.orders_banki_rfScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_banki_rfScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_banki_rfScalarWhereWithAggregatesInput | Prisma.orders_banki_rfScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_banki_rf"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"orders_banki_rf"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  timechek?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  amount?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  metod?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  dkarta?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  nameP?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  phoneP?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_banki_rf"> | string
}

export type orders_banki_rfCreateInput = {
  date?: Date | string
  name: string
  phone: string
  timechek: string
  amount: string
  metod: string
  dkarta: string
  nameP: string
  phoneP: string
  departament: string
}

export type orders_banki_rfUncheckedCreateInput = {
  id?: number
  date?: Date | string
  name: string
  phone: string
  timechek: string
  amount: string
  metod: string
  dkarta: string
  nameP: string
  phoneP: string
  departament: string
}

export type orders_banki_rfUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  timechek?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  metod?: Prisma.StringFieldUpdateOperationsInput | string
  dkarta?: Prisma.StringFieldUpdateOperationsInput | string
  nameP?: Prisma.StringFieldUpdateOperationsInput | string
  phoneP?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_banki_rfUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  timechek?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  metod?: Prisma.StringFieldUpdateOperationsInput | string
  dkarta?: Prisma.StringFieldUpdateOperationsInput | string
  nameP?: Prisma.StringFieldUpdateOperationsInput | string
  phoneP?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_banki_rfCreateManyInput = {
  id?: number
  date?: Date | string
  name: string
  phone: string
  timechek: string
  amount: string
  metod: string
  dkarta: string
  nameP: string
  phoneP: string
  departament: string
}

export type orders_banki_rfUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  timechek?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  metod?: Prisma.StringFieldUpdateOperationsInput | string
  dkarta?: Prisma.StringFieldUpdateOperationsInput | string
  nameP?: Prisma.StringFieldUpdateOperationsInput | string
  phoneP?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_banki_rfUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  timechek?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  metod?: Prisma.StringFieldUpdateOperationsInput | string
  dkarta?: Prisma.StringFieldUpdateOperationsInput | string
  nameP?: Prisma.StringFieldUpdateOperationsInput | string
  phoneP?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_banki_rfOrderByRelevanceInput = {
  fields: Prisma.orders_banki_rfOrderByRelevanceFieldEnum | Prisma.orders_banki_rfOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_banki_rfCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  timechek?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  metod?: Prisma.SortOrder
  dkarta?: Prisma.SortOrder
  nameP?: Prisma.SortOrder
  phoneP?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_banki_rfAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_banki_rfMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  timechek?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  metod?: Prisma.SortOrder
  dkarta?: Prisma.SortOrder
  nameP?: Prisma.SortOrder
  phoneP?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_banki_rfMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  timechek?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  metod?: Prisma.SortOrder
  dkarta?: Prisma.SortOrder
  nameP?: Prisma.SortOrder
  phoneP?: Prisma.SortOrder
  departament?: Prisma.SortOrder
}

export type orders_banki_rfSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_banki_rfSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  name?: boolean
  phone?: boolean
  timechek?: boolean
  amount?: boolean
  metod?: boolean
  dkarta?: boolean
  nameP?: boolean
  phoneP?: boolean
  departament?: boolean
}, ExtArgs["result"]["orders_banki_rf"]>



export type orders_banki_rfSelectScalar = {
  id?: boolean
  date?: boolean
  name?: boolean
  phone?: boolean
  timechek?: boolean
  amount?: boolean
  metod?: boolean
  dkarta?: boolean
  nameP?: boolean
  phoneP?: boolean
  departament?: boolean
}

export type orders_banki_rfOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "name" | "phone" | "timechek" | "amount" | "metod" | "dkarta" | "nameP" | "phoneP" | "departament", ExtArgs["result"]["orders_banki_rf"]>

export type $orders_banki_rfPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_banki_rf"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    name: string
    phone: string
    timechek: string
    amount: string
    metod: string
    dkarta: string
    nameP: string
    phoneP: string
    departament: string
  }, ExtArgs["result"]["orders_banki_rf"]>
  composites: {}
}

export type orders_banki_rfGetPayload<S extends boolean | null | undefined | orders_banki_rfDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload, S>

export type orders_banki_rfCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_banki_rfFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_banki_rfCountAggregateInputType | true
  }

export interface orders_banki_rfDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_banki_rf'], meta: { name: 'orders_banki_rf' } }
  /**
   * Find zero or one Orders_banki_rf that matches the filter.
   * @param {orders_banki_rfFindUniqueArgs} args - Arguments to find a Orders_banki_rf
   * @example
   * // Get one Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_banki_rfFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_banki_rfFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_banki_rf that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_banki_rfFindUniqueOrThrowArgs} args - Arguments to find a Orders_banki_rf
   * @example
   * // Get one Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_banki_rfFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_banki_rfFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_banki_rf that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfFindFirstArgs} args - Arguments to find a Orders_banki_rf
   * @example
   * // Get one Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_banki_rfFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_banki_rfFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_banki_rf that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfFindFirstOrThrowArgs} args - Arguments to find a Orders_banki_rf
   * @example
   * // Get one Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_banki_rfFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_banki_rfFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_banki_rfs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_banki_rfs
   * const orders_banki_rfs = await prisma.orders_banki_rf.findMany()
   * 
   * // Get first 10 Orders_banki_rfs
   * const orders_banki_rfs = await prisma.orders_banki_rf.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_banki_rfWithIdOnly = await prisma.orders_banki_rf.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_banki_rfFindManyArgs>(args?: Prisma.SelectSubset<T, orders_banki_rfFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_banki_rf.
   * @param {orders_banki_rfCreateArgs} args - Arguments to create a Orders_banki_rf.
   * @example
   * // Create one Orders_banki_rf
   * const Orders_banki_rf = await prisma.orders_banki_rf.create({
   *   data: {
   *     // ... data to create a Orders_banki_rf
   *   }
   * })
   * 
   */
  create<T extends orders_banki_rfCreateArgs>(args: Prisma.SelectSubset<T, orders_banki_rfCreateArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_banki_rfs.
   * @param {orders_banki_rfCreateManyArgs} args - Arguments to create many Orders_banki_rfs.
   * @example
   * // Create many Orders_banki_rfs
   * const orders_banki_rf = await prisma.orders_banki_rf.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_banki_rfCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_banki_rfCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_banki_rf.
   * @param {orders_banki_rfDeleteArgs} args - Arguments to delete one Orders_banki_rf.
   * @example
   * // Delete one Orders_banki_rf
   * const Orders_banki_rf = await prisma.orders_banki_rf.delete({
   *   where: {
   *     // ... filter to delete one Orders_banki_rf
   *   }
   * })
   * 
   */
  delete<T extends orders_banki_rfDeleteArgs>(args: Prisma.SelectSubset<T, orders_banki_rfDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_banki_rf.
   * @param {orders_banki_rfUpdateArgs} args - Arguments to update one Orders_banki_rf.
   * @example
   * // Update one Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_banki_rfUpdateArgs>(args: Prisma.SelectSubset<T, orders_banki_rfUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_banki_rfs.
   * @param {orders_banki_rfDeleteManyArgs} args - Arguments to filter Orders_banki_rfs to delete.
   * @example
   * // Delete a few Orders_banki_rfs
   * const { count } = await prisma.orders_banki_rf.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_banki_rfDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_banki_rfDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_banki_rfs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_banki_rfs
   * const orders_banki_rf = await prisma.orders_banki_rf.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_banki_rfUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_banki_rfUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_banki_rf.
   * @param {orders_banki_rfUpsertArgs} args - Arguments to update or create a Orders_banki_rf.
   * @example
   * // Update or create a Orders_banki_rf
   * const orders_banki_rf = await prisma.orders_banki_rf.upsert({
   *   create: {
   *     // ... data to create a Orders_banki_rf
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_banki_rf we want to update
   *   }
   * })
   */
  upsert<T extends orders_banki_rfUpsertArgs>(args: Prisma.SelectSubset<T, orders_banki_rfUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_banki_rfClient<runtime.Types.Result.GetResult<Prisma.$orders_banki_rfPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_banki_rfs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfCountArgs} args - Arguments to filter Orders_banki_rfs to count.
   * @example
   * // Count the number of Orders_banki_rfs
   * const count = await prisma.orders_banki_rf.count({
   *   where: {
   *     // ... the filter for the Orders_banki_rfs we want to count
   *   }
   * })
  **/
  count<T extends orders_banki_rfCountArgs>(
    args?: Prisma.Subset<T, orders_banki_rfCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_banki_rfCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_banki_rf.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_banki_rfAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_banki_rfAggregateArgs>(args: Prisma.Subset<T, Orders_banki_rfAggregateArgs>): Prisma.PrismaPromise<GetOrders_banki_rfAggregateType<T>>

  /**
   * Group by Orders_banki_rf.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_banki_rfGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_banki_rfGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_banki_rfGroupByArgs['orderBy'] }
      : { orderBy?: orders_banki_rfGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_banki_rfGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_banki_rfGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_banki_rf model
 */
readonly fields: orders_banki_rfFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_banki_rf.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_banki_rfClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_banki_rf model
 */
export interface orders_banki_rfFieldRefs {
  readonly id: Prisma.FieldRef<"orders_banki_rf", 'Int'>
  readonly date: Prisma.FieldRef<"orders_banki_rf", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly phone: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly timechek: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly amount: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly metod: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly dkarta: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly nameP: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly phoneP: Prisma.FieldRef<"orders_banki_rf", 'String'>
  readonly departament: Prisma.FieldRef<"orders_banki_rf", 'String'>
}
    

// Custom InputTypes
/**
 * orders_banki_rf findUnique
 */
export type orders_banki_rfFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter, which orders_banki_rf to fetch.
   */
  where: Prisma.orders_banki_rfWhereUniqueInput
}

/**
 * orders_banki_rf findUniqueOrThrow
 */
export type orders_banki_rfFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter, which orders_banki_rf to fetch.
   */
  where: Prisma.orders_banki_rfWhereUniqueInput
}

/**
 * orders_banki_rf findFirst
 */
export type orders_banki_rfFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter, which orders_banki_rf to fetch.
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_banki_rfs to fetch.
   */
  orderBy?: Prisma.orders_banki_rfOrderByWithRelationInput | Prisma.orders_banki_rfOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_banki_rfs.
   */
  cursor?: Prisma.orders_banki_rfWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_banki_rfs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_banki_rfs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_banki_rfs.
   */
  distinct?: Prisma.Orders_banki_rfScalarFieldEnum | Prisma.Orders_banki_rfScalarFieldEnum[]
}

/**
 * orders_banki_rf findFirstOrThrow
 */
export type orders_banki_rfFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter, which orders_banki_rf to fetch.
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_banki_rfs to fetch.
   */
  orderBy?: Prisma.orders_banki_rfOrderByWithRelationInput | Prisma.orders_banki_rfOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_banki_rfs.
   */
  cursor?: Prisma.orders_banki_rfWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_banki_rfs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_banki_rfs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_banki_rfs.
   */
  distinct?: Prisma.Orders_banki_rfScalarFieldEnum | Prisma.Orders_banki_rfScalarFieldEnum[]
}

/**
 * orders_banki_rf findMany
 */
export type orders_banki_rfFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter, which orders_banki_rfs to fetch.
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_banki_rfs to fetch.
   */
  orderBy?: Prisma.orders_banki_rfOrderByWithRelationInput | Prisma.orders_banki_rfOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_banki_rfs.
   */
  cursor?: Prisma.orders_banki_rfWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_banki_rfs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_banki_rfs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_banki_rfs.
   */
  distinct?: Prisma.Orders_banki_rfScalarFieldEnum | Prisma.Orders_banki_rfScalarFieldEnum[]
}

/**
 * orders_banki_rf create
 */
export type orders_banki_rfCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_banki_rf.
   */
  data: Prisma.XOR<Prisma.orders_banki_rfCreateInput, Prisma.orders_banki_rfUncheckedCreateInput>
}

/**
 * orders_banki_rf createMany
 */
export type orders_banki_rfCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_banki_rfs.
   */
  data: Prisma.orders_banki_rfCreateManyInput | Prisma.orders_banki_rfCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_banki_rf update
 */
export type orders_banki_rfUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_banki_rf.
   */
  data: Prisma.XOR<Prisma.orders_banki_rfUpdateInput, Prisma.orders_banki_rfUncheckedUpdateInput>
  /**
   * Choose, which orders_banki_rf to update.
   */
  where: Prisma.orders_banki_rfWhereUniqueInput
}

/**
 * orders_banki_rf updateMany
 */
export type orders_banki_rfUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_banki_rfs.
   */
  data: Prisma.XOR<Prisma.orders_banki_rfUpdateManyMutationInput, Prisma.orders_banki_rfUncheckedUpdateManyInput>
  /**
   * Filter which orders_banki_rfs to update
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * Limit how many orders_banki_rfs to update.
   */
  limit?: number
}

/**
 * orders_banki_rf upsert
 */
export type orders_banki_rfUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_banki_rf to update in case it exists.
   */
  where: Prisma.orders_banki_rfWhereUniqueInput
  /**
   * In case the orders_banki_rf found by the `where` argument doesn't exist, create a new orders_banki_rf with this data.
   */
  create: Prisma.XOR<Prisma.orders_banki_rfCreateInput, Prisma.orders_banki_rfUncheckedCreateInput>
  /**
   * In case the orders_banki_rf was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_banki_rfUpdateInput, Prisma.orders_banki_rfUncheckedUpdateInput>
}

/**
 * orders_banki_rf delete
 */
export type orders_banki_rfDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
  /**
   * Filter which orders_banki_rf to delete.
   */
  where: Prisma.orders_banki_rfWhereUniqueInput
}

/**
 * orders_banki_rf deleteMany
 */
export type orders_banki_rfDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_banki_rfs to delete
   */
  where?: Prisma.orders_banki_rfWhereInput
  /**
   * Limit how many orders_banki_rfs to delete.
   */
  limit?: number
}

/**
 * orders_banki_rf without action
 */
export type orders_banki_rfDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_banki_rf
   */
  select?: Prisma.orders_banki_rfSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_banki_rf
   */
  omit?: Prisma.orders_banki_rfOmit<ExtArgs> | null
}
