
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_dostavka_ali` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_dostavka_ali
 * 
 */
export type orders_dostavka_aliModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_dostavka_aliPayload>

export type AggregateOrders_dostavka_ali = {
  _count: Orders_dostavka_aliCountAggregateOutputType | null
  _avg: Orders_dostavka_aliAvgAggregateOutputType | null
  _sum: Orders_dostavka_aliSumAggregateOutputType | null
  _min: Orders_dostavka_aliMinAggregateOutputType | null
  _max: Orders_dostavka_aliMaxAggregateOutputType | null
}

export type Orders_dostavka_aliAvgAggregateOutputType = {
  id: number | null
}

export type Orders_dostavka_aliSumAggregateOutputType = {
  id: number | null
}

export type Orders_dostavka_aliMinAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  razmer: string | null
  color: string | null
  colvo: string | null
  amount: string | null
}

export type Orders_dostavka_aliMaxAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  razmer: string | null
  color: string | null
  colvo: string | null
  amount: string | null
}

export type Orders_dostavka_aliCountAggregateOutputType = {
  id: number
  data: number
  name: number
  phone: number
  mail: number
  departament: number
  links: number
  opisanie: number
  razmer: number
  color: number
  colvo: number
  amount: number
  _all: number
}


export type Orders_dostavka_aliAvgAggregateInputType = {
  id?: true
}

export type Orders_dostavka_aliSumAggregateInputType = {
  id?: true
}

export type Orders_dostavka_aliMinAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  razmer?: true
  color?: true
  colvo?: true
  amount?: true
}

export type Orders_dostavka_aliMaxAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  razmer?: true
  color?: true
  colvo?: true
  amount?: true
}

export type Orders_dostavka_aliCountAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  razmer?: true
  color?: true
  colvo?: true
  amount?: true
  _all?: true
}

export type Orders_dostavka_aliAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_dostavka_ali to aggregate.
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_dostavka_alis to fetch.
   */
  orderBy?: Prisma.orders_dostavka_aliOrderByWithRelationInput | Prisma.orders_dostavka_aliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_dostavka_aliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_dostavka_alis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_dostavka_alis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_dostavka_alis
  **/
  _count?: true | Orders_dostavka_aliCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_dostavka_aliAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_dostavka_aliSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_dostavka_aliMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_dostavka_aliMaxAggregateInputType
}

export type GetOrders_dostavka_aliAggregateType<T extends Orders_dostavka_aliAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_dostavka_ali]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_dostavka_ali[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_dostavka_ali[P]>
}




export type orders_dostavka_aliGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_dostavka_aliWhereInput
  orderBy?: Prisma.orders_dostavka_aliOrderByWithAggregationInput | Prisma.orders_dostavka_aliOrderByWithAggregationInput[]
  by: Prisma.Orders_dostavka_aliScalarFieldEnum[] | Prisma.Orders_dostavka_aliScalarFieldEnum
  having?: Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_dostavka_aliCountAggregateInputType | true
  _avg?: Orders_dostavka_aliAvgAggregateInputType
  _sum?: Orders_dostavka_aliSumAggregateInputType
  _min?: Orders_dostavka_aliMinAggregateInputType
  _max?: Orders_dostavka_aliMaxAggregateInputType
}

export type Orders_dostavka_aliGroupByOutputType = {
  id: number
  data: Date
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  razmer: string
  color: string
  colvo: string
  amount: string
  _count: Orders_dostavka_aliCountAggregateOutputType | null
  _avg: Orders_dostavka_aliAvgAggregateOutputType | null
  _sum: Orders_dostavka_aliSumAggregateOutputType | null
  _min: Orders_dostavka_aliMinAggregateOutputType | null
  _max: Orders_dostavka_aliMaxAggregateOutputType | null
}

export type GetOrders_dostavka_aliGroupByPayload<T extends orders_dostavka_aliGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_dostavka_aliGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_dostavka_aliGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_dostavka_aliGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_dostavka_aliGroupByOutputType[P]>
      }
    >
  >



export type orders_dostavka_aliWhereInput = {
  AND?: Prisma.orders_dostavka_aliWhereInput | Prisma.orders_dostavka_aliWhereInput[]
  OR?: Prisma.orders_dostavka_aliWhereInput[]
  NOT?: Prisma.orders_dostavka_aliWhereInput | Prisma.orders_dostavka_aliWhereInput[]
  id?: Prisma.IntFilter<"orders_dostavka_ali"> | number
  data?: Prisma.DateTimeFilter<"orders_dostavka_ali"> | Date | string
  name?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  phone?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  mail?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  departament?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  links?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  opisanie?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  razmer?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  color?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  colvo?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  amount?: Prisma.StringFilter<"orders_dostavka_ali"> | string
}

export type orders_dostavka_aliOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  razmer?: Prisma.SortOrder
  color?: Prisma.SortOrder
  colvo?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _relevance?: Prisma.orders_dostavka_aliOrderByRelevanceInput
}

export type orders_dostavka_aliWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_dostavka_aliWhereInput | Prisma.orders_dostavka_aliWhereInput[]
  OR?: Prisma.orders_dostavka_aliWhereInput[]
  NOT?: Prisma.orders_dostavka_aliWhereInput | Prisma.orders_dostavka_aliWhereInput[]
  data?: Prisma.DateTimeFilter<"orders_dostavka_ali"> | Date | string
  name?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  phone?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  mail?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  departament?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  links?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  opisanie?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  razmer?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  color?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  colvo?: Prisma.StringFilter<"orders_dostavka_ali"> | string
  amount?: Prisma.StringFilter<"orders_dostavka_ali"> | string
}, "id">

export type orders_dostavka_aliOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  razmer?: Prisma.SortOrder
  color?: Prisma.SortOrder
  colvo?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _count?: Prisma.orders_dostavka_aliCountOrderByAggregateInput
  _avg?: Prisma.orders_dostavka_aliAvgOrderByAggregateInput
  _max?: Prisma.orders_dostavka_aliMaxOrderByAggregateInput
  _min?: Prisma.orders_dostavka_aliMinOrderByAggregateInput
  _sum?: Prisma.orders_dostavka_aliSumOrderByAggregateInput
}

export type orders_dostavka_aliScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput | Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput | Prisma.orders_dostavka_aliScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_dostavka_ali"> | number
  data?: Prisma.DateTimeWithAggregatesFilter<"orders_dostavka_ali"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  mail?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  links?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  opisanie?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  razmer?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  color?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  colvo?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
  amount?: Prisma.StringWithAggregatesFilter<"orders_dostavka_ali"> | string
}

export type orders_dostavka_aliCreateInput = {
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  razmer: string
  color: string
  colvo: string
  amount: string
}

export type orders_dostavka_aliUncheckedCreateInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  razmer: string
  color: string
  colvo: string
  amount: string
}

export type orders_dostavka_aliUpdateInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  razmer?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  colvo?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_dostavka_aliUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  razmer?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  colvo?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_dostavka_aliCreateManyInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  razmer: string
  color: string
  colvo: string
  amount: string
}

export type orders_dostavka_aliUpdateManyMutationInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  razmer?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  colvo?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_dostavka_aliUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  razmer?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  colvo?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_dostavka_aliOrderByRelevanceInput = {
  fields: Prisma.orders_dostavka_aliOrderByRelevanceFieldEnum | Prisma.orders_dostavka_aliOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_dostavka_aliCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  razmer?: Prisma.SortOrder
  color?: Prisma.SortOrder
  colvo?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_dostavka_aliAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_dostavka_aliMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  razmer?: Prisma.SortOrder
  color?: Prisma.SortOrder
  colvo?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_dostavka_aliMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  razmer?: Prisma.SortOrder
  color?: Prisma.SortOrder
  colvo?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_dostavka_aliSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_dostavka_aliSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  razmer?: boolean
  color?: boolean
  colvo?: boolean
  amount?: boolean
}, ExtArgs["result"]["orders_dostavka_ali"]>



export type orders_dostavka_aliSelectScalar = {
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  razmer?: boolean
  color?: boolean
  colvo?: boolean
  amount?: boolean
}

export type orders_dostavka_aliOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "name" | "phone" | "mail" | "departament" | "links" | "opisanie" | "razmer" | "color" | "colvo" | "amount", ExtArgs["result"]["orders_dostavka_ali"]>

export type $orders_dostavka_aliPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_dostavka_ali"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    data: Date
    name: string
    phone: string
    mail: string
    departament: string
    links: string
    opisanie: string
    razmer: string
    color: string
    colvo: string
    amount: string
  }, ExtArgs["result"]["orders_dostavka_ali"]>
  composites: {}
}

export type orders_dostavka_aliGetPayload<S extends boolean | null | undefined | orders_dostavka_aliDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload, S>

export type orders_dostavka_aliCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_dostavka_aliFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_dostavka_aliCountAggregateInputType | true
  }

export interface orders_dostavka_aliDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_dostavka_ali'], meta: { name: 'orders_dostavka_ali' } }
  /**
   * Find zero or one Orders_dostavka_ali that matches the filter.
   * @param {orders_dostavka_aliFindUniqueArgs} args - Arguments to find a Orders_dostavka_ali
   * @example
   * // Get one Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_dostavka_aliFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_dostavka_ali that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_dostavka_aliFindUniqueOrThrowArgs} args - Arguments to find a Orders_dostavka_ali
   * @example
   * // Get one Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_dostavka_aliFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_dostavka_ali that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliFindFirstArgs} args - Arguments to find a Orders_dostavka_ali
   * @example
   * // Get one Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_dostavka_aliFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_dostavka_aliFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_dostavka_ali that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliFindFirstOrThrowArgs} args - Arguments to find a Orders_dostavka_ali
   * @example
   * // Get one Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_dostavka_aliFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_dostavka_aliFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_dostavka_alis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_dostavka_alis
   * const orders_dostavka_alis = await prisma.orders_dostavka_ali.findMany()
   * 
   * // Get first 10 Orders_dostavka_alis
   * const orders_dostavka_alis = await prisma.orders_dostavka_ali.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_dostavka_aliWithIdOnly = await prisma.orders_dostavka_ali.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_dostavka_aliFindManyArgs>(args?: Prisma.SelectSubset<T, orders_dostavka_aliFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_dostavka_ali.
   * @param {orders_dostavka_aliCreateArgs} args - Arguments to create a Orders_dostavka_ali.
   * @example
   * // Create one Orders_dostavka_ali
   * const Orders_dostavka_ali = await prisma.orders_dostavka_ali.create({
   *   data: {
   *     // ... data to create a Orders_dostavka_ali
   *   }
   * })
   * 
   */
  create<T extends orders_dostavka_aliCreateArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliCreateArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_dostavka_alis.
   * @param {orders_dostavka_aliCreateManyArgs} args - Arguments to create many Orders_dostavka_alis.
   * @example
   * // Create many Orders_dostavka_alis
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_dostavka_aliCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_dostavka_aliCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_dostavka_ali.
   * @param {orders_dostavka_aliDeleteArgs} args - Arguments to delete one Orders_dostavka_ali.
   * @example
   * // Delete one Orders_dostavka_ali
   * const Orders_dostavka_ali = await prisma.orders_dostavka_ali.delete({
   *   where: {
   *     // ... filter to delete one Orders_dostavka_ali
   *   }
   * })
   * 
   */
  delete<T extends orders_dostavka_aliDeleteArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_dostavka_ali.
   * @param {orders_dostavka_aliUpdateArgs} args - Arguments to update one Orders_dostavka_ali.
   * @example
   * // Update one Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_dostavka_aliUpdateArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_dostavka_alis.
   * @param {orders_dostavka_aliDeleteManyArgs} args - Arguments to filter Orders_dostavka_alis to delete.
   * @example
   * // Delete a few Orders_dostavka_alis
   * const { count } = await prisma.orders_dostavka_ali.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_dostavka_aliDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_dostavka_aliDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_dostavka_alis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_dostavka_alis
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_dostavka_aliUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_dostavka_ali.
   * @param {orders_dostavka_aliUpsertArgs} args - Arguments to update or create a Orders_dostavka_ali.
   * @example
   * // Update or create a Orders_dostavka_ali
   * const orders_dostavka_ali = await prisma.orders_dostavka_ali.upsert({
   *   create: {
   *     // ... data to create a Orders_dostavka_ali
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_dostavka_ali we want to update
   *   }
   * })
   */
  upsert<T extends orders_dostavka_aliUpsertArgs>(args: Prisma.SelectSubset<T, orders_dostavka_aliUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_dostavka_aliClient<runtime.Types.Result.GetResult<Prisma.$orders_dostavka_aliPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_dostavka_alis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliCountArgs} args - Arguments to filter Orders_dostavka_alis to count.
   * @example
   * // Count the number of Orders_dostavka_alis
   * const count = await prisma.orders_dostavka_ali.count({
   *   where: {
   *     // ... the filter for the Orders_dostavka_alis we want to count
   *   }
   * })
  **/
  count<T extends orders_dostavka_aliCountArgs>(
    args?: Prisma.Subset<T, orders_dostavka_aliCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_dostavka_aliCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_dostavka_ali.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_dostavka_aliAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_dostavka_aliAggregateArgs>(args: Prisma.Subset<T, Orders_dostavka_aliAggregateArgs>): Prisma.PrismaPromise<GetOrders_dostavka_aliAggregateType<T>>

  /**
   * Group by Orders_dostavka_ali.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_dostavka_aliGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_dostavka_aliGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_dostavka_aliGroupByArgs['orderBy'] }
      : { orderBy?: orders_dostavka_aliGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_dostavka_aliGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_dostavka_aliGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_dostavka_ali model
 */
readonly fields: orders_dostavka_aliFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_dostavka_ali.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_dostavka_aliClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_dostavka_ali model
 */
export interface orders_dostavka_aliFieldRefs {
  readonly id: Prisma.FieldRef<"orders_dostavka_ali", 'Int'>
  readonly data: Prisma.FieldRef<"orders_dostavka_ali", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly phone: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly mail: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly departament: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly links: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly opisanie: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly razmer: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly color: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly colvo: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
  readonly amount: Prisma.FieldRef<"orders_dostavka_ali", 'String'>
}
    

// Custom InputTypes
/**
 * orders_dostavka_ali findUnique
 */
export type orders_dostavka_aliFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter, which orders_dostavka_ali to fetch.
   */
  where: Prisma.orders_dostavka_aliWhereUniqueInput
}

/**
 * orders_dostavka_ali findUniqueOrThrow
 */
export type orders_dostavka_aliFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter, which orders_dostavka_ali to fetch.
   */
  where: Prisma.orders_dostavka_aliWhereUniqueInput
}

/**
 * orders_dostavka_ali findFirst
 */
export type orders_dostavka_aliFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter, which orders_dostavka_ali to fetch.
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_dostavka_alis to fetch.
   */
  orderBy?: Prisma.orders_dostavka_aliOrderByWithRelationInput | Prisma.orders_dostavka_aliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_dostavka_alis.
   */
  cursor?: Prisma.orders_dostavka_aliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_dostavka_alis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_dostavka_alis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_dostavka_alis.
   */
  distinct?: Prisma.Orders_dostavka_aliScalarFieldEnum | Prisma.Orders_dostavka_aliScalarFieldEnum[]
}

/**
 * orders_dostavka_ali findFirstOrThrow
 */
export type orders_dostavka_aliFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter, which orders_dostavka_ali to fetch.
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_dostavka_alis to fetch.
   */
  orderBy?: Prisma.orders_dostavka_aliOrderByWithRelationInput | Prisma.orders_dostavka_aliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_dostavka_alis.
   */
  cursor?: Prisma.orders_dostavka_aliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_dostavka_alis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_dostavka_alis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_dostavka_alis.
   */
  distinct?: Prisma.Orders_dostavka_aliScalarFieldEnum | Prisma.Orders_dostavka_aliScalarFieldEnum[]
}

/**
 * orders_dostavka_ali findMany
 */
export type orders_dostavka_aliFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter, which orders_dostavka_alis to fetch.
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_dostavka_alis to fetch.
   */
  orderBy?: Prisma.orders_dostavka_aliOrderByWithRelationInput | Prisma.orders_dostavka_aliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_dostavka_alis.
   */
  cursor?: Prisma.orders_dostavka_aliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_dostavka_alis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_dostavka_alis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_dostavka_alis.
   */
  distinct?: Prisma.Orders_dostavka_aliScalarFieldEnum | Prisma.Orders_dostavka_aliScalarFieldEnum[]
}

/**
 * orders_dostavka_ali create
 */
export type orders_dostavka_aliCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_dostavka_ali.
   */
  data: Prisma.XOR<Prisma.orders_dostavka_aliCreateInput, Prisma.orders_dostavka_aliUncheckedCreateInput>
}

/**
 * orders_dostavka_ali createMany
 */
export type orders_dostavka_aliCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_dostavka_alis.
   */
  data: Prisma.orders_dostavka_aliCreateManyInput | Prisma.orders_dostavka_aliCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_dostavka_ali update
 */
export type orders_dostavka_aliUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_dostavka_ali.
   */
  data: Prisma.XOR<Prisma.orders_dostavka_aliUpdateInput, Prisma.orders_dostavka_aliUncheckedUpdateInput>
  /**
   * Choose, which orders_dostavka_ali to update.
   */
  where: Prisma.orders_dostavka_aliWhereUniqueInput
}

/**
 * orders_dostavka_ali updateMany
 */
export type orders_dostavka_aliUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_dostavka_alis.
   */
  data: Prisma.XOR<Prisma.orders_dostavka_aliUpdateManyMutationInput, Prisma.orders_dostavka_aliUncheckedUpdateManyInput>
  /**
   * Filter which orders_dostavka_alis to update
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * Limit how many orders_dostavka_alis to update.
   */
  limit?: number
}

/**
 * orders_dostavka_ali upsert
 */
export type orders_dostavka_aliUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_dostavka_ali to update in case it exists.
   */
  where: Prisma.orders_dostavka_aliWhereUniqueInput
  /**
   * In case the orders_dostavka_ali found by the `where` argument doesn't exist, create a new orders_dostavka_ali with this data.
   */
  create: Prisma.XOR<Prisma.orders_dostavka_aliCreateInput, Prisma.orders_dostavka_aliUncheckedCreateInput>
  /**
   * In case the orders_dostavka_ali was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_dostavka_aliUpdateInput, Prisma.orders_dostavka_aliUncheckedUpdateInput>
}

/**
 * orders_dostavka_ali delete
 */
export type orders_dostavka_aliDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
  /**
   * Filter which orders_dostavka_ali to delete.
   */
  where: Prisma.orders_dostavka_aliWhereUniqueInput
}

/**
 * orders_dostavka_ali deleteMany
 */
export type orders_dostavka_aliDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_dostavka_alis to delete
   */
  where?: Prisma.orders_dostavka_aliWhereInput
  /**
   * Limit how many orders_dostavka_alis to delete.
   */
  limit?: number
}

/**
 * orders_dostavka_ali without action
 */
export type orders_dostavka_aliDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_dostavka_ali
   */
  select?: Prisma.orders_dostavka_aliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_dostavka_ali
   */
  omit?: Prisma.orders_dostavka_aliOmit<ExtArgs> | null
}
