
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_temernik` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_temernik
 * 
 */
export type orders_temernikModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_temernikPayload>

export type AggregateOrders_temernik = {
  _count: Orders_temernikCountAggregateOutputType | null
  _avg: Orders_temernikAvgAggregateOutputType | null
  _sum: Orders_temernikSumAggregateOutputType | null
  _min: Orders_temernikMinAggregateOutputType | null
  _max: Orders_temernikMaxAggregateOutputType | null
}

export type Orders_temernikAvgAggregateOutputType = {
  id: number | null
}

export type Orders_temernikSumAggregateOutputType = {
  id: number | null
}

export type Orders_temernikMinAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  amount: string | null
}

export type Orders_temernikMaxAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  amount: string | null
}

export type Orders_temernikCountAggregateOutputType = {
  id: number
  data: number
  name: number
  phone: number
  mail: number
  departament: number
  links: number
  opisanie: number
  amount: number
  _all: number
}


export type Orders_temernikAvgAggregateInputType = {
  id?: true
}

export type Orders_temernikSumAggregateInputType = {
  id?: true
}

export type Orders_temernikMinAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
}

export type Orders_temernikMaxAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
}

export type Orders_temernikCountAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
  _all?: true
}

export type Orders_temernikAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_temernik to aggregate.
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_temerniks to fetch.
   */
  orderBy?: Prisma.orders_temernikOrderByWithRelationInput | Prisma.orders_temernikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_temernikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_temerniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_temerniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_temerniks
  **/
  _count?: true | Orders_temernikCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_temernikAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_temernikSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_temernikMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_temernikMaxAggregateInputType
}

export type GetOrders_temernikAggregateType<T extends Orders_temernikAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_temernik]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_temernik[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_temernik[P]>
}




export type orders_temernikGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_temernikWhereInput
  orderBy?: Prisma.orders_temernikOrderByWithAggregationInput | Prisma.orders_temernikOrderByWithAggregationInput[]
  by: Prisma.Orders_temernikScalarFieldEnum[] | Prisma.Orders_temernikScalarFieldEnum
  having?: Prisma.orders_temernikScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_temernikCountAggregateInputType | true
  _avg?: Orders_temernikAvgAggregateInputType
  _sum?: Orders_temernikSumAggregateInputType
  _min?: Orders_temernikMinAggregateInputType
  _max?: Orders_temernikMaxAggregateInputType
}

export type Orders_temernikGroupByOutputType = {
  id: number
  data: Date
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
  _count: Orders_temernikCountAggregateOutputType | null
  _avg: Orders_temernikAvgAggregateOutputType | null
  _sum: Orders_temernikSumAggregateOutputType | null
  _min: Orders_temernikMinAggregateOutputType | null
  _max: Orders_temernikMaxAggregateOutputType | null
}

export type GetOrders_temernikGroupByPayload<T extends orders_temernikGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_temernikGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_temernikGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_temernikGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_temernikGroupByOutputType[P]>
      }
    >
  >



export type orders_temernikWhereInput = {
  AND?: Prisma.orders_temernikWhereInput | Prisma.orders_temernikWhereInput[]
  OR?: Prisma.orders_temernikWhereInput[]
  NOT?: Prisma.orders_temernikWhereInput | Prisma.orders_temernikWhereInput[]
  id?: Prisma.IntFilter<"orders_temernik"> | number
  data?: Prisma.DateTimeFilter<"orders_temernik"> | Date | string
  name?: Prisma.StringFilter<"orders_temernik"> | string
  phone?: Prisma.StringFilter<"orders_temernik"> | string
  mail?: Prisma.StringFilter<"orders_temernik"> | string
  departament?: Prisma.StringFilter<"orders_temernik"> | string
  links?: Prisma.StringFilter<"orders_temernik"> | string
  opisanie?: Prisma.StringFilter<"orders_temernik"> | string
  amount?: Prisma.StringFilter<"orders_temernik"> | string
}

export type orders_temernikOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _relevance?: Prisma.orders_temernikOrderByRelevanceInput
}

export type orders_temernikWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_temernikWhereInput | Prisma.orders_temernikWhereInput[]
  OR?: Prisma.orders_temernikWhereInput[]
  NOT?: Prisma.orders_temernikWhereInput | Prisma.orders_temernikWhereInput[]
  data?: Prisma.DateTimeFilter<"orders_temernik"> | Date | string
  name?: Prisma.StringFilter<"orders_temernik"> | string
  phone?: Prisma.StringFilter<"orders_temernik"> | string
  mail?: Prisma.StringFilter<"orders_temernik"> | string
  departament?: Prisma.StringFilter<"orders_temernik"> | string
  links?: Prisma.StringFilter<"orders_temernik"> | string
  opisanie?: Prisma.StringFilter<"orders_temernik"> | string
  amount?: Prisma.StringFilter<"orders_temernik"> | string
}, "id">

export type orders_temernikOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _count?: Prisma.orders_temernikCountOrderByAggregateInput
  _avg?: Prisma.orders_temernikAvgOrderByAggregateInput
  _max?: Prisma.orders_temernikMaxOrderByAggregateInput
  _min?: Prisma.orders_temernikMinOrderByAggregateInput
  _sum?: Prisma.orders_temernikSumOrderByAggregateInput
}

export type orders_temernikScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_temernikScalarWhereWithAggregatesInput | Prisma.orders_temernikScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_temernikScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_temernikScalarWhereWithAggregatesInput | Prisma.orders_temernikScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_temernik"> | number
  data?: Prisma.DateTimeWithAggregatesFilter<"orders_temernik"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  mail?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  links?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  opisanie?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
  amount?: Prisma.StringWithAggregatesFilter<"orders_temernik"> | string
}

export type orders_temernikCreateInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_temernikUncheckedCreateInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_temernikUpdateInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_temernikUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_temernikCreateManyInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_temernikUpdateManyMutationInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_temernikUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_temernikOrderByRelevanceInput = {
  fields: Prisma.orders_temernikOrderByRelevanceFieldEnum | Prisma.orders_temernikOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_temernikCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_temernikAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_temernikMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_temernikMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_temernikSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_temernikSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  amount?: boolean
}, ExtArgs["result"]["orders_temernik"]>



export type orders_temernikSelectScalar = {
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  amount?: boolean
}

export type orders_temernikOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "name" | "phone" | "mail" | "departament" | "links" | "opisanie" | "amount", ExtArgs["result"]["orders_temernik"]>

export type $orders_temernikPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_temernik"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    data: Date
    name: string
    phone: string
    mail: string
    departament: string
    links: string
    opisanie: string
    amount: string
  }, ExtArgs["result"]["orders_temernik"]>
  composites: {}
}

export type orders_temernikGetPayload<S extends boolean | null | undefined | orders_temernikDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload, S>

export type orders_temernikCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_temernikFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_temernikCountAggregateInputType | true
  }

export interface orders_temernikDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_temernik'], meta: { name: 'orders_temernik' } }
  /**
   * Find zero or one Orders_temernik that matches the filter.
   * @param {orders_temernikFindUniqueArgs} args - Arguments to find a Orders_temernik
   * @example
   * // Get one Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_temernikFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_temernikFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_temernik that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_temernikFindUniqueOrThrowArgs} args - Arguments to find a Orders_temernik
   * @example
   * // Get one Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_temernikFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_temernikFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_temernik that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikFindFirstArgs} args - Arguments to find a Orders_temernik
   * @example
   * // Get one Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_temernikFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_temernikFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_temernik that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikFindFirstOrThrowArgs} args - Arguments to find a Orders_temernik
   * @example
   * // Get one Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_temernikFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_temernikFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_temerniks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_temerniks
   * const orders_temerniks = await prisma.orders_temernik.findMany()
   * 
   * // Get first 10 Orders_temerniks
   * const orders_temerniks = await prisma.orders_temernik.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_temernikWithIdOnly = await prisma.orders_temernik.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_temernikFindManyArgs>(args?: Prisma.SelectSubset<T, orders_temernikFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_temernik.
   * @param {orders_temernikCreateArgs} args - Arguments to create a Orders_temernik.
   * @example
   * // Create one Orders_temernik
   * const Orders_temernik = await prisma.orders_temernik.create({
   *   data: {
   *     // ... data to create a Orders_temernik
   *   }
   * })
   * 
   */
  create<T extends orders_temernikCreateArgs>(args: Prisma.SelectSubset<T, orders_temernikCreateArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_temerniks.
   * @param {orders_temernikCreateManyArgs} args - Arguments to create many Orders_temerniks.
   * @example
   * // Create many Orders_temerniks
   * const orders_temernik = await prisma.orders_temernik.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_temernikCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_temernikCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_temernik.
   * @param {orders_temernikDeleteArgs} args - Arguments to delete one Orders_temernik.
   * @example
   * // Delete one Orders_temernik
   * const Orders_temernik = await prisma.orders_temernik.delete({
   *   where: {
   *     // ... filter to delete one Orders_temernik
   *   }
   * })
   * 
   */
  delete<T extends orders_temernikDeleteArgs>(args: Prisma.SelectSubset<T, orders_temernikDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_temernik.
   * @param {orders_temernikUpdateArgs} args - Arguments to update one Orders_temernik.
   * @example
   * // Update one Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_temernikUpdateArgs>(args: Prisma.SelectSubset<T, orders_temernikUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_temerniks.
   * @param {orders_temernikDeleteManyArgs} args - Arguments to filter Orders_temerniks to delete.
   * @example
   * // Delete a few Orders_temerniks
   * const { count } = await prisma.orders_temernik.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_temernikDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_temernikDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_temerniks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_temerniks
   * const orders_temernik = await prisma.orders_temernik.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_temernikUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_temernikUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_temernik.
   * @param {orders_temernikUpsertArgs} args - Arguments to update or create a Orders_temernik.
   * @example
   * // Update or create a Orders_temernik
   * const orders_temernik = await prisma.orders_temernik.upsert({
   *   create: {
   *     // ... data to create a Orders_temernik
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_temernik we want to update
   *   }
   * })
   */
  upsert<T extends orders_temernikUpsertArgs>(args: Prisma.SelectSubset<T, orders_temernikUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_temernikClient<runtime.Types.Result.GetResult<Prisma.$orders_temernikPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_temerniks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikCountArgs} args - Arguments to filter Orders_temerniks to count.
   * @example
   * // Count the number of Orders_temerniks
   * const count = await prisma.orders_temernik.count({
   *   where: {
   *     // ... the filter for the Orders_temerniks we want to count
   *   }
   * })
  **/
  count<T extends orders_temernikCountArgs>(
    args?: Prisma.Subset<T, orders_temernikCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_temernikCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_temernik.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_temernikAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_temernikAggregateArgs>(args: Prisma.Subset<T, Orders_temernikAggregateArgs>): Prisma.PrismaPromise<GetOrders_temernikAggregateType<T>>

  /**
   * Group by Orders_temernik.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_temernikGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_temernikGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_temernikGroupByArgs['orderBy'] }
      : { orderBy?: orders_temernikGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_temernikGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_temernikGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_temernik model
 */
readonly fields: orders_temernikFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_temernik.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_temernikClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_temernik model
 */
export interface orders_temernikFieldRefs {
  readonly id: Prisma.FieldRef<"orders_temernik", 'Int'>
  readonly data: Prisma.FieldRef<"orders_temernik", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly phone: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly mail: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly departament: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly links: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly opisanie: Prisma.FieldRef<"orders_temernik", 'String'>
  readonly amount: Prisma.FieldRef<"orders_temernik", 'String'>
}
    

// Custom InputTypes
/**
 * orders_temernik findUnique
 */
export type orders_temernikFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter, which orders_temernik to fetch.
   */
  where: Prisma.orders_temernikWhereUniqueInput
}

/**
 * orders_temernik findUniqueOrThrow
 */
export type orders_temernikFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter, which orders_temernik to fetch.
   */
  where: Prisma.orders_temernikWhereUniqueInput
}

/**
 * orders_temernik findFirst
 */
export type orders_temernikFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter, which orders_temernik to fetch.
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_temerniks to fetch.
   */
  orderBy?: Prisma.orders_temernikOrderByWithRelationInput | Prisma.orders_temernikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_temerniks.
   */
  cursor?: Prisma.orders_temernikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_temerniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_temerniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_temerniks.
   */
  distinct?: Prisma.Orders_temernikScalarFieldEnum | Prisma.Orders_temernikScalarFieldEnum[]
}

/**
 * orders_temernik findFirstOrThrow
 */
export type orders_temernikFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter, which orders_temernik to fetch.
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_temerniks to fetch.
   */
  orderBy?: Prisma.orders_temernikOrderByWithRelationInput | Prisma.orders_temernikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_temerniks.
   */
  cursor?: Prisma.orders_temernikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_temerniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_temerniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_temerniks.
   */
  distinct?: Prisma.Orders_temernikScalarFieldEnum | Prisma.Orders_temernikScalarFieldEnum[]
}

/**
 * orders_temernik findMany
 */
export type orders_temernikFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter, which orders_temerniks to fetch.
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_temerniks to fetch.
   */
  orderBy?: Prisma.orders_temernikOrderByWithRelationInput | Prisma.orders_temernikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_temerniks.
   */
  cursor?: Prisma.orders_temernikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_temerniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_temerniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_temerniks.
   */
  distinct?: Prisma.Orders_temernikScalarFieldEnum | Prisma.Orders_temernikScalarFieldEnum[]
}

/**
 * orders_temernik create
 */
export type orders_temernikCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_temernik.
   */
  data: Prisma.XOR<Prisma.orders_temernikCreateInput, Prisma.orders_temernikUncheckedCreateInput>
}

/**
 * orders_temernik createMany
 */
export type orders_temernikCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_temerniks.
   */
  data: Prisma.orders_temernikCreateManyInput | Prisma.orders_temernikCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_temernik update
 */
export type orders_temernikUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_temernik.
   */
  data: Prisma.XOR<Prisma.orders_temernikUpdateInput, Prisma.orders_temernikUncheckedUpdateInput>
  /**
   * Choose, which orders_temernik to update.
   */
  where: Prisma.orders_temernikWhereUniqueInput
}

/**
 * orders_temernik updateMany
 */
export type orders_temernikUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_temerniks.
   */
  data: Prisma.XOR<Prisma.orders_temernikUpdateManyMutationInput, Prisma.orders_temernikUncheckedUpdateManyInput>
  /**
   * Filter which orders_temerniks to update
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * Limit how many orders_temerniks to update.
   */
  limit?: number
}

/**
 * orders_temernik upsert
 */
export type orders_temernikUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_temernik to update in case it exists.
   */
  where: Prisma.orders_temernikWhereUniqueInput
  /**
   * In case the orders_temernik found by the `where` argument doesn't exist, create a new orders_temernik with this data.
   */
  create: Prisma.XOR<Prisma.orders_temernikCreateInput, Prisma.orders_temernikUncheckedCreateInput>
  /**
   * In case the orders_temernik was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_temernikUpdateInput, Prisma.orders_temernikUncheckedUpdateInput>
}

/**
 * orders_temernik delete
 */
export type orders_temernikDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
  /**
   * Filter which orders_temernik to delete.
   */
  where: Prisma.orders_temernikWhereUniqueInput
}

/**
 * orders_temernik deleteMany
 */
export type orders_temernikDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_temerniks to delete
   */
  where?: Prisma.orders_temernikWhereInput
  /**
   * Limit how many orders_temerniks to delete.
   */
  limit?: number
}

/**
 * orders_temernik without action
 */
export type orders_temernikDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_temernik
   */
  select?: Prisma.orders_temernikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_temernik
   */
  omit?: Prisma.orders_temernikOmit<ExtArgs> | null
}
