
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_sadovod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_sadovod
 * 
 */
export type orders_sadovodModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_sadovodPayload>

export type AggregateOrders_sadovod = {
  _count: Orders_sadovodCountAggregateOutputType | null
  _avg: Orders_sadovodAvgAggregateOutputType | null
  _sum: Orders_sadovodSumAggregateOutputType | null
  _min: Orders_sadovodMinAggregateOutputType | null
  _max: Orders_sadovodMaxAggregateOutputType | null
}

export type Orders_sadovodAvgAggregateOutputType = {
  id: number | null
}

export type Orders_sadovodSumAggregateOutputType = {
  id: number | null
}

export type Orders_sadovodMinAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  amount: string | null
}

export type Orders_sadovodMaxAggregateOutputType = {
  id: number | null
  data: Date | null
  name: string | null
  phone: string | null
  mail: string | null
  departament: string | null
  links: string | null
  opisanie: string | null
  amount: string | null
}

export type Orders_sadovodCountAggregateOutputType = {
  id: number
  data: number
  name: number
  phone: number
  mail: number
  departament: number
  links: number
  opisanie: number
  amount: number
  _all: number
}


export type Orders_sadovodAvgAggregateInputType = {
  id?: true
}

export type Orders_sadovodSumAggregateInputType = {
  id?: true
}

export type Orders_sadovodMinAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
}

export type Orders_sadovodMaxAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
}

export type Orders_sadovodCountAggregateInputType = {
  id?: true
  data?: true
  name?: true
  phone?: true
  mail?: true
  departament?: true
  links?: true
  opisanie?: true
  amount?: true
  _all?: true
}

export type Orders_sadovodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_sadovod to aggregate.
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_sadovods to fetch.
   */
  orderBy?: Prisma.orders_sadovodOrderByWithRelationInput | Prisma.orders_sadovodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_sadovodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_sadovods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_sadovods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_sadovods
  **/
  _count?: true | Orders_sadovodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_sadovodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_sadovodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_sadovodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_sadovodMaxAggregateInputType
}

export type GetOrders_sadovodAggregateType<T extends Orders_sadovodAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_sadovod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_sadovod[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_sadovod[P]>
}




export type orders_sadovodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_sadovodWhereInput
  orderBy?: Prisma.orders_sadovodOrderByWithAggregationInput | Prisma.orders_sadovodOrderByWithAggregationInput[]
  by: Prisma.Orders_sadovodScalarFieldEnum[] | Prisma.Orders_sadovodScalarFieldEnum
  having?: Prisma.orders_sadovodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_sadovodCountAggregateInputType | true
  _avg?: Orders_sadovodAvgAggregateInputType
  _sum?: Orders_sadovodSumAggregateInputType
  _min?: Orders_sadovodMinAggregateInputType
  _max?: Orders_sadovodMaxAggregateInputType
}

export type Orders_sadovodGroupByOutputType = {
  id: number
  data: Date
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
  _count: Orders_sadovodCountAggregateOutputType | null
  _avg: Orders_sadovodAvgAggregateOutputType | null
  _sum: Orders_sadovodSumAggregateOutputType | null
  _min: Orders_sadovodMinAggregateOutputType | null
  _max: Orders_sadovodMaxAggregateOutputType | null
}

export type GetOrders_sadovodGroupByPayload<T extends orders_sadovodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_sadovodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_sadovodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_sadovodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_sadovodGroupByOutputType[P]>
      }
    >
  >



export type orders_sadovodWhereInput = {
  AND?: Prisma.orders_sadovodWhereInput | Prisma.orders_sadovodWhereInput[]
  OR?: Prisma.orders_sadovodWhereInput[]
  NOT?: Prisma.orders_sadovodWhereInput | Prisma.orders_sadovodWhereInput[]
  id?: Prisma.IntFilter<"orders_sadovod"> | number
  data?: Prisma.DateTimeFilter<"orders_sadovod"> | Date | string
  name?: Prisma.StringFilter<"orders_sadovod"> | string
  phone?: Prisma.StringFilter<"orders_sadovod"> | string
  mail?: Prisma.StringFilter<"orders_sadovod"> | string
  departament?: Prisma.StringFilter<"orders_sadovod"> | string
  links?: Prisma.StringFilter<"orders_sadovod"> | string
  opisanie?: Prisma.StringFilter<"orders_sadovod"> | string
  amount?: Prisma.StringFilter<"orders_sadovod"> | string
}

export type orders_sadovodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _relevance?: Prisma.orders_sadovodOrderByRelevanceInput
}

export type orders_sadovodWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_sadovodWhereInput | Prisma.orders_sadovodWhereInput[]
  OR?: Prisma.orders_sadovodWhereInput[]
  NOT?: Prisma.orders_sadovodWhereInput | Prisma.orders_sadovodWhereInput[]
  data?: Prisma.DateTimeFilter<"orders_sadovod"> | Date | string
  name?: Prisma.StringFilter<"orders_sadovod"> | string
  phone?: Prisma.StringFilter<"orders_sadovod"> | string
  mail?: Prisma.StringFilter<"orders_sadovod"> | string
  departament?: Prisma.StringFilter<"orders_sadovod"> | string
  links?: Prisma.StringFilter<"orders_sadovod"> | string
  opisanie?: Prisma.StringFilter<"orders_sadovod"> | string
  amount?: Prisma.StringFilter<"orders_sadovod"> | string
}, "id">

export type orders_sadovodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _count?: Prisma.orders_sadovodCountOrderByAggregateInput
  _avg?: Prisma.orders_sadovodAvgOrderByAggregateInput
  _max?: Prisma.orders_sadovodMaxOrderByAggregateInput
  _min?: Prisma.orders_sadovodMinOrderByAggregateInput
  _sum?: Prisma.orders_sadovodSumOrderByAggregateInput
}

export type orders_sadovodScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_sadovodScalarWhereWithAggregatesInput | Prisma.orders_sadovodScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_sadovodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_sadovodScalarWhereWithAggregatesInput | Prisma.orders_sadovodScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_sadovod"> | number
  data?: Prisma.DateTimeWithAggregatesFilter<"orders_sadovod"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  mail?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  links?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  opisanie?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
  amount?: Prisma.StringWithAggregatesFilter<"orders_sadovod"> | string
}

export type orders_sadovodCreateInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_sadovodUncheckedCreateInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_sadovodUpdateInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_sadovodUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_sadovodCreateManyInput = {
  id?: number
  data?: Date | string
  name: string
  phone: string
  mail: string
  departament: string
  links: string
  opisanie: string
  amount: string
}

export type orders_sadovodUpdateManyMutationInput = {
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_sadovodUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_sadovodOrderByRelevanceInput = {
  fields: Prisma.orders_sadovodOrderByRelevanceFieldEnum | Prisma.orders_sadovodOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_sadovodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_sadovodAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_sadovodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_sadovodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type orders_sadovodSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_sadovodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  amount?: boolean
}, ExtArgs["result"]["orders_sadovod"]>



export type orders_sadovodSelectScalar = {
  id?: boolean
  data?: boolean
  name?: boolean
  phone?: boolean
  mail?: boolean
  departament?: boolean
  links?: boolean
  opisanie?: boolean
  amount?: boolean
}

export type orders_sadovodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "name" | "phone" | "mail" | "departament" | "links" | "opisanie" | "amount", ExtArgs["result"]["orders_sadovod"]>

export type $orders_sadovodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_sadovod"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    data: Date
    name: string
    phone: string
    mail: string
    departament: string
    links: string
    opisanie: string
    amount: string
  }, ExtArgs["result"]["orders_sadovod"]>
  composites: {}
}

export type orders_sadovodGetPayload<S extends boolean | null | undefined | orders_sadovodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload, S>

export type orders_sadovodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_sadovodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_sadovodCountAggregateInputType | true
  }

export interface orders_sadovodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_sadovod'], meta: { name: 'orders_sadovod' } }
  /**
   * Find zero or one Orders_sadovod that matches the filter.
   * @param {orders_sadovodFindUniqueArgs} args - Arguments to find a Orders_sadovod
   * @example
   * // Get one Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_sadovodFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_sadovodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_sadovod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_sadovodFindUniqueOrThrowArgs} args - Arguments to find a Orders_sadovod
   * @example
   * // Get one Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_sadovodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_sadovodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_sadovod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodFindFirstArgs} args - Arguments to find a Orders_sadovod
   * @example
   * // Get one Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_sadovodFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_sadovodFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_sadovod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodFindFirstOrThrowArgs} args - Arguments to find a Orders_sadovod
   * @example
   * // Get one Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_sadovodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_sadovodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_sadovods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_sadovods
   * const orders_sadovods = await prisma.orders_sadovod.findMany()
   * 
   * // Get first 10 Orders_sadovods
   * const orders_sadovods = await prisma.orders_sadovod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_sadovodWithIdOnly = await prisma.orders_sadovod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_sadovodFindManyArgs>(args?: Prisma.SelectSubset<T, orders_sadovodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_sadovod.
   * @param {orders_sadovodCreateArgs} args - Arguments to create a Orders_sadovod.
   * @example
   * // Create one Orders_sadovod
   * const Orders_sadovod = await prisma.orders_sadovod.create({
   *   data: {
   *     // ... data to create a Orders_sadovod
   *   }
   * })
   * 
   */
  create<T extends orders_sadovodCreateArgs>(args: Prisma.SelectSubset<T, orders_sadovodCreateArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_sadovods.
   * @param {orders_sadovodCreateManyArgs} args - Arguments to create many Orders_sadovods.
   * @example
   * // Create many Orders_sadovods
   * const orders_sadovod = await prisma.orders_sadovod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_sadovodCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_sadovodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_sadovod.
   * @param {orders_sadovodDeleteArgs} args - Arguments to delete one Orders_sadovod.
   * @example
   * // Delete one Orders_sadovod
   * const Orders_sadovod = await prisma.orders_sadovod.delete({
   *   where: {
   *     // ... filter to delete one Orders_sadovod
   *   }
   * })
   * 
   */
  delete<T extends orders_sadovodDeleteArgs>(args: Prisma.SelectSubset<T, orders_sadovodDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_sadovod.
   * @param {orders_sadovodUpdateArgs} args - Arguments to update one Orders_sadovod.
   * @example
   * // Update one Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_sadovodUpdateArgs>(args: Prisma.SelectSubset<T, orders_sadovodUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_sadovods.
   * @param {orders_sadovodDeleteManyArgs} args - Arguments to filter Orders_sadovods to delete.
   * @example
   * // Delete a few Orders_sadovods
   * const { count } = await prisma.orders_sadovod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_sadovodDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_sadovodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_sadovods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_sadovods
   * const orders_sadovod = await prisma.orders_sadovod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_sadovodUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_sadovodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_sadovod.
   * @param {orders_sadovodUpsertArgs} args - Arguments to update or create a Orders_sadovod.
   * @example
   * // Update or create a Orders_sadovod
   * const orders_sadovod = await prisma.orders_sadovod.upsert({
   *   create: {
   *     // ... data to create a Orders_sadovod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_sadovod we want to update
   *   }
   * })
   */
  upsert<T extends orders_sadovodUpsertArgs>(args: Prisma.SelectSubset<T, orders_sadovodUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_sadovodClient<runtime.Types.Result.GetResult<Prisma.$orders_sadovodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_sadovods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodCountArgs} args - Arguments to filter Orders_sadovods to count.
   * @example
   * // Count the number of Orders_sadovods
   * const count = await prisma.orders_sadovod.count({
   *   where: {
   *     // ... the filter for the Orders_sadovods we want to count
   *   }
   * })
  **/
  count<T extends orders_sadovodCountArgs>(
    args?: Prisma.Subset<T, orders_sadovodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_sadovodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_sadovod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_sadovodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_sadovodAggregateArgs>(args: Prisma.Subset<T, Orders_sadovodAggregateArgs>): Prisma.PrismaPromise<GetOrders_sadovodAggregateType<T>>

  /**
   * Group by Orders_sadovod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_sadovodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_sadovodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_sadovodGroupByArgs['orderBy'] }
      : { orderBy?: orders_sadovodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_sadovodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_sadovodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_sadovod model
 */
readonly fields: orders_sadovodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_sadovod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_sadovodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_sadovod model
 */
export interface orders_sadovodFieldRefs {
  readonly id: Prisma.FieldRef<"orders_sadovod", 'Int'>
  readonly data: Prisma.FieldRef<"orders_sadovod", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly phone: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly mail: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly departament: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly links: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly opisanie: Prisma.FieldRef<"orders_sadovod", 'String'>
  readonly amount: Prisma.FieldRef<"orders_sadovod", 'String'>
}
    

// Custom InputTypes
/**
 * orders_sadovod findUnique
 */
export type orders_sadovodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter, which orders_sadovod to fetch.
   */
  where: Prisma.orders_sadovodWhereUniqueInput
}

/**
 * orders_sadovod findUniqueOrThrow
 */
export type orders_sadovodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter, which orders_sadovod to fetch.
   */
  where: Prisma.orders_sadovodWhereUniqueInput
}

/**
 * orders_sadovod findFirst
 */
export type orders_sadovodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter, which orders_sadovod to fetch.
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_sadovods to fetch.
   */
  orderBy?: Prisma.orders_sadovodOrderByWithRelationInput | Prisma.orders_sadovodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_sadovods.
   */
  cursor?: Prisma.orders_sadovodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_sadovods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_sadovods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_sadovods.
   */
  distinct?: Prisma.Orders_sadovodScalarFieldEnum | Prisma.Orders_sadovodScalarFieldEnum[]
}

/**
 * orders_sadovod findFirstOrThrow
 */
export type orders_sadovodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter, which orders_sadovod to fetch.
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_sadovods to fetch.
   */
  orderBy?: Prisma.orders_sadovodOrderByWithRelationInput | Prisma.orders_sadovodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_sadovods.
   */
  cursor?: Prisma.orders_sadovodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_sadovods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_sadovods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_sadovods.
   */
  distinct?: Prisma.Orders_sadovodScalarFieldEnum | Prisma.Orders_sadovodScalarFieldEnum[]
}

/**
 * orders_sadovod findMany
 */
export type orders_sadovodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter, which orders_sadovods to fetch.
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_sadovods to fetch.
   */
  orderBy?: Prisma.orders_sadovodOrderByWithRelationInput | Prisma.orders_sadovodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_sadovods.
   */
  cursor?: Prisma.orders_sadovodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_sadovods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_sadovods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_sadovods.
   */
  distinct?: Prisma.Orders_sadovodScalarFieldEnum | Prisma.Orders_sadovodScalarFieldEnum[]
}

/**
 * orders_sadovod create
 */
export type orders_sadovodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_sadovod.
   */
  data: Prisma.XOR<Prisma.orders_sadovodCreateInput, Prisma.orders_sadovodUncheckedCreateInput>
}

/**
 * orders_sadovod createMany
 */
export type orders_sadovodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_sadovods.
   */
  data: Prisma.orders_sadovodCreateManyInput | Prisma.orders_sadovodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_sadovod update
 */
export type orders_sadovodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_sadovod.
   */
  data: Prisma.XOR<Prisma.orders_sadovodUpdateInput, Prisma.orders_sadovodUncheckedUpdateInput>
  /**
   * Choose, which orders_sadovod to update.
   */
  where: Prisma.orders_sadovodWhereUniqueInput
}

/**
 * orders_sadovod updateMany
 */
export type orders_sadovodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_sadovods.
   */
  data: Prisma.XOR<Prisma.orders_sadovodUpdateManyMutationInput, Prisma.orders_sadovodUncheckedUpdateManyInput>
  /**
   * Filter which orders_sadovods to update
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * Limit how many orders_sadovods to update.
   */
  limit?: number
}

/**
 * orders_sadovod upsert
 */
export type orders_sadovodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_sadovod to update in case it exists.
   */
  where: Prisma.orders_sadovodWhereUniqueInput
  /**
   * In case the orders_sadovod found by the `where` argument doesn't exist, create a new orders_sadovod with this data.
   */
  create: Prisma.XOR<Prisma.orders_sadovodCreateInput, Prisma.orders_sadovodUncheckedCreateInput>
  /**
   * In case the orders_sadovod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_sadovodUpdateInput, Prisma.orders_sadovodUncheckedUpdateInput>
}

/**
 * orders_sadovod delete
 */
export type orders_sadovodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
  /**
   * Filter which orders_sadovod to delete.
   */
  where: Prisma.orders_sadovodWhereUniqueInput
}

/**
 * orders_sadovod deleteMany
 */
export type orders_sadovodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_sadovods to delete
   */
  where?: Prisma.orders_sadovodWhereInput
  /**
   * Limit how many orders_sadovods to delete.
   */
  limit?: number
}

/**
 * orders_sadovod without action
 */
export type orders_sadovodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_sadovod
   */
  select?: Prisma.orders_sadovodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_sadovod
   */
  omit?: Prisma.orders_sadovodOmit<ExtArgs> | null
}
