
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders_aliexpress_krym` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model orders_aliexpress_krym
 * 
 */
export type orders_aliexpress_krymModel = runtime.Types.Result.DefaultSelection<Prisma.$orders_aliexpress_krymPayload>

export type AggregateOrders_aliexpress_krym = {
  _count: Orders_aliexpress_krymCountAggregateOutputType | null
  _avg: Orders_aliexpress_krymAvgAggregateOutputType | null
  _sum: Orders_aliexpress_krymSumAggregateOutputType | null
  _min: Orders_aliexpress_krymMinAggregateOutputType | null
  _max: Orders_aliexpress_krymMaxAggregateOutputType | null
}

export type Orders_aliexpress_krymAvgAggregateOutputType = {
  id: number | null
}

export type Orders_aliexpress_krymSumAggregateOutputType = {
  id: number | null
}

export type Orders_aliexpress_krymMinAggregateOutputType = {
  id: number | null
  date: Date | null
  name: string | null
  phone: string | null
  passport: string | null
  vidan: string | null
  kogda: string | null
  pasldnr: string | null
  departament: string | null
  links: string | null
  amount: string | null
  name_Otpravitelya: string | null
  TK: string | null
  track_number: string | null
  mail: string | null
  citi_otprav: string | null
  phone_otprav: string | null
  kto_oplachivaet: string | null
  opisanie: string | null
  VIP: string | null
}

export type Orders_aliexpress_krymMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  name: string | null
  phone: string | null
  passport: string | null
  vidan: string | null
  kogda: string | null
  pasldnr: string | null
  departament: string | null
  links: string | null
  amount: string | null
  name_Otpravitelya: string | null
  TK: string | null
  track_number: string | null
  mail: string | null
  citi_otprav: string | null
  phone_otprav: string | null
  kto_oplachivaet: string | null
  opisanie: string | null
  VIP: string | null
}

export type Orders_aliexpress_krymCountAggregateOutputType = {
  id: number
  date: number
  name: number
  phone: number
  passport: number
  vidan: number
  kogda: number
  pasldnr: number
  departament: number
  links: number
  amount: number
  name_Otpravitelya: number
  TK: number
  track_number: number
  mail: number
  citi_otprav: number
  phone_otprav: number
  kto_oplachivaet: number
  opisanie: number
  VIP: number
  _all: number
}


export type Orders_aliexpress_krymAvgAggregateInputType = {
  id?: true
}

export type Orders_aliexpress_krymSumAggregateInputType = {
  id?: true
}

export type Orders_aliexpress_krymMinAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  passport?: true
  vidan?: true
  kogda?: true
  pasldnr?: true
  departament?: true
  links?: true
  amount?: true
  name_Otpravitelya?: true
  TK?: true
  track_number?: true
  mail?: true
  citi_otprav?: true
  phone_otprav?: true
  kto_oplachivaet?: true
  opisanie?: true
  VIP?: true
}

export type Orders_aliexpress_krymMaxAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  passport?: true
  vidan?: true
  kogda?: true
  pasldnr?: true
  departament?: true
  links?: true
  amount?: true
  name_Otpravitelya?: true
  TK?: true
  track_number?: true
  mail?: true
  citi_otprav?: true
  phone_otprav?: true
  kto_oplachivaet?: true
  opisanie?: true
  VIP?: true
}

export type Orders_aliexpress_krymCountAggregateInputType = {
  id?: true
  date?: true
  name?: true
  phone?: true
  passport?: true
  vidan?: true
  kogda?: true
  pasldnr?: true
  departament?: true
  links?: true
  amount?: true
  name_Otpravitelya?: true
  TK?: true
  track_number?: true
  mail?: true
  citi_otprav?: true
  phone_otprav?: true
  kto_oplachivaet?: true
  opisanie?: true
  VIP?: true
  _all?: true
}

export type Orders_aliexpress_krymAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_aliexpress_krym to aggregate.
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_aliexpress_kryms to fetch.
   */
  orderBy?: Prisma.orders_aliexpress_krymOrderByWithRelationInput | Prisma.orders_aliexpress_krymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orders_aliexpress_krymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_aliexpress_kryms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_aliexpress_kryms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders_aliexpress_kryms
  **/
  _count?: true | Orders_aliexpress_krymCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Orders_aliexpress_krymAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Orders_aliexpress_krymSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Orders_aliexpress_krymMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Orders_aliexpress_krymMaxAggregateInputType
}

export type GetOrders_aliexpress_krymAggregateType<T extends Orders_aliexpress_krymAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders_aliexpress_krym]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders_aliexpress_krym[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders_aliexpress_krym[P]>
}




export type orders_aliexpress_krymGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orders_aliexpress_krymWhereInput
  orderBy?: Prisma.orders_aliexpress_krymOrderByWithAggregationInput | Prisma.orders_aliexpress_krymOrderByWithAggregationInput[]
  by: Prisma.Orders_aliexpress_krymScalarFieldEnum[] | Prisma.Orders_aliexpress_krymScalarFieldEnum
  having?: Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Orders_aliexpress_krymCountAggregateInputType | true
  _avg?: Orders_aliexpress_krymAvgAggregateInputType
  _sum?: Orders_aliexpress_krymSumAggregateInputType
  _min?: Orders_aliexpress_krymMinAggregateInputType
  _max?: Orders_aliexpress_krymMaxAggregateInputType
}

export type Orders_aliexpress_krymGroupByOutputType = {
  id: number
  date: Date | null
  name: string
  phone: string
  passport: string
  vidan: string
  kogda: string
  pasldnr: string
  departament: string
  links: string
  amount: string
  name_Otpravitelya: string
  TK: string
  track_number: string
  mail: string
  citi_otprav: string
  phone_otprav: string
  kto_oplachivaet: string
  opisanie: string
  VIP: string
  _count: Orders_aliexpress_krymCountAggregateOutputType | null
  _avg: Orders_aliexpress_krymAvgAggregateOutputType | null
  _sum: Orders_aliexpress_krymSumAggregateOutputType | null
  _min: Orders_aliexpress_krymMinAggregateOutputType | null
  _max: Orders_aliexpress_krymMaxAggregateOutputType | null
}

export type GetOrders_aliexpress_krymGroupByPayload<T extends orders_aliexpress_krymGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Orders_aliexpress_krymGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Orders_aliexpress_krymGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Orders_aliexpress_krymGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Orders_aliexpress_krymGroupByOutputType[P]>
      }
    >
  >



export type orders_aliexpress_krymWhereInput = {
  AND?: Prisma.orders_aliexpress_krymWhereInput | Prisma.orders_aliexpress_krymWhereInput[]
  OR?: Prisma.orders_aliexpress_krymWhereInput[]
  NOT?: Prisma.orders_aliexpress_krymWhereInput | Prisma.orders_aliexpress_krymWhereInput[]
  id?: Prisma.IntFilter<"orders_aliexpress_krym"> | number
  date?: Prisma.DateTimeNullableFilter<"orders_aliexpress_krym"> | Date | string | null
  name?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  phone?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  passport?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  vidan?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  kogda?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  pasldnr?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  departament?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  links?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  amount?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  name_Otpravitelya?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  TK?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  track_number?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  mail?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  citi_otprav?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  phone_otprav?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  kto_oplachivaet?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  opisanie?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  VIP?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
}

export type orders_aliexpress_krymOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  passport?: Prisma.SortOrder
  vidan?: Prisma.SortOrder
  kogda?: Prisma.SortOrder
  pasldnr?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  name_Otpravitelya?: Prisma.SortOrder
  TK?: Prisma.SortOrder
  track_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  citi_otprav?: Prisma.SortOrder
  phone_otprav?: Prisma.SortOrder
  kto_oplachivaet?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  VIP?: Prisma.SortOrder
  _relevance?: Prisma.orders_aliexpress_krymOrderByRelevanceInput
}

export type orders_aliexpress_krymWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orders_aliexpress_krymWhereInput | Prisma.orders_aliexpress_krymWhereInput[]
  OR?: Prisma.orders_aliexpress_krymWhereInput[]
  NOT?: Prisma.orders_aliexpress_krymWhereInput | Prisma.orders_aliexpress_krymWhereInput[]
  date?: Prisma.DateTimeNullableFilter<"orders_aliexpress_krym"> | Date | string | null
  name?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  phone?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  passport?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  vidan?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  kogda?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  pasldnr?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  departament?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  links?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  amount?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  name_Otpravitelya?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  TK?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  track_number?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  mail?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  citi_otprav?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  phone_otprav?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  kto_oplachivaet?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  opisanie?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
  VIP?: Prisma.StringFilter<"orders_aliexpress_krym"> | string
}, "id">

export type orders_aliexpress_krymOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  passport?: Prisma.SortOrder
  vidan?: Prisma.SortOrder
  kogda?: Prisma.SortOrder
  pasldnr?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  name_Otpravitelya?: Prisma.SortOrder
  TK?: Prisma.SortOrder
  track_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  citi_otprav?: Prisma.SortOrder
  phone_otprav?: Prisma.SortOrder
  kto_oplachivaet?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  VIP?: Prisma.SortOrder
  _count?: Prisma.orders_aliexpress_krymCountOrderByAggregateInput
  _avg?: Prisma.orders_aliexpress_krymAvgOrderByAggregateInput
  _max?: Prisma.orders_aliexpress_krymMaxOrderByAggregateInput
  _min?: Prisma.orders_aliexpress_krymMinOrderByAggregateInput
  _sum?: Prisma.orders_aliexpress_krymSumOrderByAggregateInput
}

export type orders_aliexpress_krymScalarWhereWithAggregatesInput = {
  AND?: Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput | Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput[]
  OR?: Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput | Prisma.orders_aliexpress_krymScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders_aliexpress_krym"> | number
  date?: Prisma.DateTimeNullableWithAggregatesFilter<"orders_aliexpress_krym"> | Date | string | null
  name?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  phone?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  passport?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  vidan?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  kogda?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  pasldnr?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  departament?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  links?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  amount?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  name_Otpravitelya?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  TK?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  track_number?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  mail?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  citi_otprav?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  phone_otprav?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  kto_oplachivaet?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  opisanie?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
  VIP?: Prisma.StringWithAggregatesFilter<"orders_aliexpress_krym"> | string
}

export type orders_aliexpress_krymCreateInput = {
  date?: Date | string | null
  name: string
  phone: string
  passport: string
  vidan: string
  kogda: string
  pasldnr: string
  departament: string
  links: string
  amount: string
  name_Otpravitelya: string
  TK: string
  track_number: string
  mail: string
  citi_otprav: string
  phone_otprav: string
  kto_oplachivaet: string
  opisanie: string
  VIP: string
}

export type orders_aliexpress_krymUncheckedCreateInput = {
  id?: number
  date?: Date | string | null
  name: string
  phone: string
  passport: string
  vidan: string
  kogda: string
  pasldnr: string
  departament: string
  links: string
  amount: string
  name_Otpravitelya: string
  TK: string
  track_number: string
  mail: string
  citi_otprav: string
  phone_otprav: string
  kto_oplachivaet: string
  opisanie: string
  VIP: string
}

export type orders_aliexpress_krymUpdateInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  passport?: Prisma.StringFieldUpdateOperationsInput | string
  vidan?: Prisma.StringFieldUpdateOperationsInput | string
  kogda?: Prisma.StringFieldUpdateOperationsInput | string
  pasldnr?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  name_Otpravitelya?: Prisma.StringFieldUpdateOperationsInput | string
  TK?: Prisma.StringFieldUpdateOperationsInput | string
  track_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  citi_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  phone_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  kto_oplachivaet?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  VIP?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_aliexpress_krymUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  passport?: Prisma.StringFieldUpdateOperationsInput | string
  vidan?: Prisma.StringFieldUpdateOperationsInput | string
  kogda?: Prisma.StringFieldUpdateOperationsInput | string
  pasldnr?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  name_Otpravitelya?: Prisma.StringFieldUpdateOperationsInput | string
  TK?: Prisma.StringFieldUpdateOperationsInput | string
  track_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  citi_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  phone_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  kto_oplachivaet?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  VIP?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_aliexpress_krymCreateManyInput = {
  id?: number
  date?: Date | string | null
  name: string
  phone: string
  passport: string
  vidan: string
  kogda: string
  pasldnr: string
  departament: string
  links: string
  amount: string
  name_Otpravitelya: string
  TK: string
  track_number: string
  mail: string
  citi_otprav: string
  phone_otprav: string
  kto_oplachivaet: string
  opisanie: string
  VIP: string
}

export type orders_aliexpress_krymUpdateManyMutationInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  passport?: Prisma.StringFieldUpdateOperationsInput | string
  vidan?: Prisma.StringFieldUpdateOperationsInput | string
  kogda?: Prisma.StringFieldUpdateOperationsInput | string
  pasldnr?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  name_Otpravitelya?: Prisma.StringFieldUpdateOperationsInput | string
  TK?: Prisma.StringFieldUpdateOperationsInput | string
  track_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  citi_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  phone_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  kto_oplachivaet?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  VIP?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_aliexpress_krymUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  passport?: Prisma.StringFieldUpdateOperationsInput | string
  vidan?: Prisma.StringFieldUpdateOperationsInput | string
  kogda?: Prisma.StringFieldUpdateOperationsInput | string
  pasldnr?: Prisma.StringFieldUpdateOperationsInput | string
  departament?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.StringFieldUpdateOperationsInput | string
  name_Otpravitelya?: Prisma.StringFieldUpdateOperationsInput | string
  TK?: Prisma.StringFieldUpdateOperationsInput | string
  track_number?: Prisma.StringFieldUpdateOperationsInput | string
  mail?: Prisma.StringFieldUpdateOperationsInput | string
  citi_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  phone_otprav?: Prisma.StringFieldUpdateOperationsInput | string
  kto_oplachivaet?: Prisma.StringFieldUpdateOperationsInput | string
  opisanie?: Prisma.StringFieldUpdateOperationsInput | string
  VIP?: Prisma.StringFieldUpdateOperationsInput | string
}

export type orders_aliexpress_krymOrderByRelevanceInput = {
  fields: Prisma.orders_aliexpress_krymOrderByRelevanceFieldEnum | Prisma.orders_aliexpress_krymOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type orders_aliexpress_krymCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  passport?: Prisma.SortOrder
  vidan?: Prisma.SortOrder
  kogda?: Prisma.SortOrder
  pasldnr?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  name_Otpravitelya?: Prisma.SortOrder
  TK?: Prisma.SortOrder
  track_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  citi_otprav?: Prisma.SortOrder
  phone_otprav?: Prisma.SortOrder
  kto_oplachivaet?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  VIP?: Prisma.SortOrder
}

export type orders_aliexpress_krymAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type orders_aliexpress_krymMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  passport?: Prisma.SortOrder
  vidan?: Prisma.SortOrder
  kogda?: Prisma.SortOrder
  pasldnr?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  name_Otpravitelya?: Prisma.SortOrder
  TK?: Prisma.SortOrder
  track_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  citi_otprav?: Prisma.SortOrder
  phone_otprav?: Prisma.SortOrder
  kto_oplachivaet?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  VIP?: Prisma.SortOrder
}

export type orders_aliexpress_krymMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  passport?: Prisma.SortOrder
  vidan?: Prisma.SortOrder
  kogda?: Prisma.SortOrder
  pasldnr?: Prisma.SortOrder
  departament?: Prisma.SortOrder
  links?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  name_Otpravitelya?: Prisma.SortOrder
  TK?: Prisma.SortOrder
  track_number?: Prisma.SortOrder
  mail?: Prisma.SortOrder
  citi_otprav?: Prisma.SortOrder
  phone_otprav?: Prisma.SortOrder
  kto_oplachivaet?: Prisma.SortOrder
  opisanie?: Prisma.SortOrder
  VIP?: Prisma.SortOrder
}

export type orders_aliexpress_krymSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type orders_aliexpress_krymSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  name?: boolean
  phone?: boolean
  passport?: boolean
  vidan?: boolean
  kogda?: boolean
  pasldnr?: boolean
  departament?: boolean
  links?: boolean
  amount?: boolean
  name_Otpravitelya?: boolean
  TK?: boolean
  track_number?: boolean
  mail?: boolean
  citi_otprav?: boolean
  phone_otprav?: boolean
  kto_oplachivaet?: boolean
  opisanie?: boolean
  VIP?: boolean
}, ExtArgs["result"]["orders_aliexpress_krym"]>



export type orders_aliexpress_krymSelectScalar = {
  id?: boolean
  date?: boolean
  name?: boolean
  phone?: boolean
  passport?: boolean
  vidan?: boolean
  kogda?: boolean
  pasldnr?: boolean
  departament?: boolean
  links?: boolean
  amount?: boolean
  name_Otpravitelya?: boolean
  TK?: boolean
  track_number?: boolean
  mail?: boolean
  citi_otprav?: boolean
  phone_otprav?: boolean
  kto_oplachivaet?: boolean
  opisanie?: boolean
  VIP?: boolean
}

export type orders_aliexpress_krymOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "name" | "phone" | "passport" | "vidan" | "kogda" | "pasldnr" | "departament" | "links" | "amount" | "name_Otpravitelya" | "TK" | "track_number" | "mail" | "citi_otprav" | "phone_otprav" | "kto_oplachivaet" | "opisanie" | "VIP", ExtArgs["result"]["orders_aliexpress_krym"]>

export type $orders_aliexpress_krymPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders_aliexpress_krym"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date | null
    name: string
    phone: string
    passport: string
    vidan: string
    kogda: string
    pasldnr: string
    departament: string
    links: string
    amount: string
    name_Otpravitelya: string
    TK: string
    track_number: string
    mail: string
    citi_otprav: string
    phone_otprav: string
    kto_oplachivaet: string
    opisanie: string
    VIP: string
  }, ExtArgs["result"]["orders_aliexpress_krym"]>
  composites: {}
}

export type orders_aliexpress_krymGetPayload<S extends boolean | null | undefined | orders_aliexpress_krymDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload, S>

export type orders_aliexpress_krymCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orders_aliexpress_krymFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Orders_aliexpress_krymCountAggregateInputType | true
  }

export interface orders_aliexpress_krymDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders_aliexpress_krym'], meta: { name: 'orders_aliexpress_krym' } }
  /**
   * Find zero or one Orders_aliexpress_krym that matches the filter.
   * @param {orders_aliexpress_krymFindUniqueArgs} args - Arguments to find a Orders_aliexpress_krym
   * @example
   * // Get one Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orders_aliexpress_krymFindUniqueArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders_aliexpress_krym that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orders_aliexpress_krymFindUniqueOrThrowArgs} args - Arguments to find a Orders_aliexpress_krym
   * @example
   * // Get one Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orders_aliexpress_krymFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_aliexpress_krym that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymFindFirstArgs} args - Arguments to find a Orders_aliexpress_krym
   * @example
   * // Get one Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orders_aliexpress_krymFindFirstArgs>(args?: Prisma.SelectSubset<T, orders_aliexpress_krymFindFirstArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders_aliexpress_krym that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymFindFirstOrThrowArgs} args - Arguments to find a Orders_aliexpress_krym
   * @example
   * // Get one Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orders_aliexpress_krymFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orders_aliexpress_krymFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders_aliexpress_kryms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders_aliexpress_kryms
   * const orders_aliexpress_kryms = await prisma.orders_aliexpress_krym.findMany()
   * 
   * // Get first 10 Orders_aliexpress_kryms
   * const orders_aliexpress_kryms = await prisma.orders_aliexpress_krym.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orders_aliexpress_krymWithIdOnly = await prisma.orders_aliexpress_krym.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orders_aliexpress_krymFindManyArgs>(args?: Prisma.SelectSubset<T, orders_aliexpress_krymFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders_aliexpress_krym.
   * @param {orders_aliexpress_krymCreateArgs} args - Arguments to create a Orders_aliexpress_krym.
   * @example
   * // Create one Orders_aliexpress_krym
   * const Orders_aliexpress_krym = await prisma.orders_aliexpress_krym.create({
   *   data: {
   *     // ... data to create a Orders_aliexpress_krym
   *   }
   * })
   * 
   */
  create<T extends orders_aliexpress_krymCreateArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymCreateArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders_aliexpress_kryms.
   * @param {orders_aliexpress_krymCreateManyArgs} args - Arguments to create many Orders_aliexpress_kryms.
   * @example
   * // Create many Orders_aliexpress_kryms
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orders_aliexpress_krymCreateManyArgs>(args?: Prisma.SelectSubset<T, orders_aliexpress_krymCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Orders_aliexpress_krym.
   * @param {orders_aliexpress_krymDeleteArgs} args - Arguments to delete one Orders_aliexpress_krym.
   * @example
   * // Delete one Orders_aliexpress_krym
   * const Orders_aliexpress_krym = await prisma.orders_aliexpress_krym.delete({
   *   where: {
   *     // ... filter to delete one Orders_aliexpress_krym
   *   }
   * })
   * 
   */
  delete<T extends orders_aliexpress_krymDeleteArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymDeleteArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders_aliexpress_krym.
   * @param {orders_aliexpress_krymUpdateArgs} args - Arguments to update one Orders_aliexpress_krym.
   * @example
   * // Update one Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orders_aliexpress_krymUpdateArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymUpdateArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders_aliexpress_kryms.
   * @param {orders_aliexpress_krymDeleteManyArgs} args - Arguments to filter Orders_aliexpress_kryms to delete.
   * @example
   * // Delete a few Orders_aliexpress_kryms
   * const { count } = await prisma.orders_aliexpress_krym.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orders_aliexpress_krymDeleteManyArgs>(args?: Prisma.SelectSubset<T, orders_aliexpress_krymDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders_aliexpress_kryms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders_aliexpress_kryms
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orders_aliexpress_krymUpdateManyArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Orders_aliexpress_krym.
   * @param {orders_aliexpress_krymUpsertArgs} args - Arguments to update or create a Orders_aliexpress_krym.
   * @example
   * // Update or create a Orders_aliexpress_krym
   * const orders_aliexpress_krym = await prisma.orders_aliexpress_krym.upsert({
   *   create: {
   *     // ... data to create a Orders_aliexpress_krym
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders_aliexpress_krym we want to update
   *   }
   * })
   */
  upsert<T extends orders_aliexpress_krymUpsertArgs>(args: Prisma.SelectSubset<T, orders_aliexpress_krymUpsertArgs<ExtArgs>>): Prisma.Prisma__orders_aliexpress_krymClient<runtime.Types.Result.GetResult<Prisma.$orders_aliexpress_krymPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders_aliexpress_kryms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymCountArgs} args - Arguments to filter Orders_aliexpress_kryms to count.
   * @example
   * // Count the number of Orders_aliexpress_kryms
   * const count = await prisma.orders_aliexpress_krym.count({
   *   where: {
   *     // ... the filter for the Orders_aliexpress_kryms we want to count
   *   }
   * })
  **/
  count<T extends orders_aliexpress_krymCountArgs>(
    args?: Prisma.Subset<T, orders_aliexpress_krymCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Orders_aliexpress_krymCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders_aliexpress_krym.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Orders_aliexpress_krymAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Orders_aliexpress_krymAggregateArgs>(args: Prisma.Subset<T, Orders_aliexpress_krymAggregateArgs>): Prisma.PrismaPromise<GetOrders_aliexpress_krymAggregateType<T>>

  /**
   * Group by Orders_aliexpress_krym.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orders_aliexpress_krymGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orders_aliexpress_krymGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orders_aliexpress_krymGroupByArgs['orderBy'] }
      : { orderBy?: orders_aliexpress_krymGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orders_aliexpress_krymGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrders_aliexpress_krymGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders_aliexpress_krym model
 */
readonly fields: orders_aliexpress_krymFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders_aliexpress_krym.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orders_aliexpress_krymClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders_aliexpress_krym model
 */
export interface orders_aliexpress_krymFieldRefs {
  readonly id: Prisma.FieldRef<"orders_aliexpress_krym", 'Int'>
  readonly date: Prisma.FieldRef<"orders_aliexpress_krym", 'DateTime'>
  readonly name: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly phone: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly passport: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly vidan: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly kogda: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly pasldnr: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly departament: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly links: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly amount: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly name_Otpravitelya: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly TK: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly track_number: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly mail: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly citi_otprav: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly phone_otprav: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly kto_oplachivaet: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly opisanie: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
  readonly VIP: Prisma.FieldRef<"orders_aliexpress_krym", 'String'>
}
    

// Custom InputTypes
/**
 * orders_aliexpress_krym findUnique
 */
export type orders_aliexpress_krymFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter, which orders_aliexpress_krym to fetch.
   */
  where: Prisma.orders_aliexpress_krymWhereUniqueInput
}

/**
 * orders_aliexpress_krym findUniqueOrThrow
 */
export type orders_aliexpress_krymFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter, which orders_aliexpress_krym to fetch.
   */
  where: Prisma.orders_aliexpress_krymWhereUniqueInput
}

/**
 * orders_aliexpress_krym findFirst
 */
export type orders_aliexpress_krymFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter, which orders_aliexpress_krym to fetch.
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_aliexpress_kryms to fetch.
   */
  orderBy?: Prisma.orders_aliexpress_krymOrderByWithRelationInput | Prisma.orders_aliexpress_krymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_aliexpress_kryms.
   */
  cursor?: Prisma.orders_aliexpress_krymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_aliexpress_kryms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_aliexpress_kryms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_aliexpress_kryms.
   */
  distinct?: Prisma.Orders_aliexpress_krymScalarFieldEnum | Prisma.Orders_aliexpress_krymScalarFieldEnum[]
}

/**
 * orders_aliexpress_krym findFirstOrThrow
 */
export type orders_aliexpress_krymFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter, which orders_aliexpress_krym to fetch.
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_aliexpress_kryms to fetch.
   */
  orderBy?: Prisma.orders_aliexpress_krymOrderByWithRelationInput | Prisma.orders_aliexpress_krymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders_aliexpress_kryms.
   */
  cursor?: Prisma.orders_aliexpress_krymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_aliexpress_kryms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_aliexpress_kryms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_aliexpress_kryms.
   */
  distinct?: Prisma.Orders_aliexpress_krymScalarFieldEnum | Prisma.Orders_aliexpress_krymScalarFieldEnum[]
}

/**
 * orders_aliexpress_krym findMany
 */
export type orders_aliexpress_krymFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter, which orders_aliexpress_kryms to fetch.
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders_aliexpress_kryms to fetch.
   */
  orderBy?: Prisma.orders_aliexpress_krymOrderByWithRelationInput | Prisma.orders_aliexpress_krymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders_aliexpress_kryms.
   */
  cursor?: Prisma.orders_aliexpress_krymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders_aliexpress_kryms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders_aliexpress_kryms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders_aliexpress_kryms.
   */
  distinct?: Prisma.Orders_aliexpress_krymScalarFieldEnum | Prisma.Orders_aliexpress_krymScalarFieldEnum[]
}

/**
 * orders_aliexpress_krym create
 */
export type orders_aliexpress_krymCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * The data needed to create a orders_aliexpress_krym.
   */
  data: Prisma.XOR<Prisma.orders_aliexpress_krymCreateInput, Prisma.orders_aliexpress_krymUncheckedCreateInput>
}

/**
 * orders_aliexpress_krym createMany
 */
export type orders_aliexpress_krymCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders_aliexpress_kryms.
   */
  data: Prisma.orders_aliexpress_krymCreateManyInput | Prisma.orders_aliexpress_krymCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders_aliexpress_krym update
 */
export type orders_aliexpress_krymUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * The data needed to update a orders_aliexpress_krym.
   */
  data: Prisma.XOR<Prisma.orders_aliexpress_krymUpdateInput, Prisma.orders_aliexpress_krymUncheckedUpdateInput>
  /**
   * Choose, which orders_aliexpress_krym to update.
   */
  where: Prisma.orders_aliexpress_krymWhereUniqueInput
}

/**
 * orders_aliexpress_krym updateMany
 */
export type orders_aliexpress_krymUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders_aliexpress_kryms.
   */
  data: Prisma.XOR<Prisma.orders_aliexpress_krymUpdateManyMutationInput, Prisma.orders_aliexpress_krymUncheckedUpdateManyInput>
  /**
   * Filter which orders_aliexpress_kryms to update
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * Limit how many orders_aliexpress_kryms to update.
   */
  limit?: number
}

/**
 * orders_aliexpress_krym upsert
 */
export type orders_aliexpress_krymUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * The filter to search for the orders_aliexpress_krym to update in case it exists.
   */
  where: Prisma.orders_aliexpress_krymWhereUniqueInput
  /**
   * In case the orders_aliexpress_krym found by the `where` argument doesn't exist, create a new orders_aliexpress_krym with this data.
   */
  create: Prisma.XOR<Prisma.orders_aliexpress_krymCreateInput, Prisma.orders_aliexpress_krymUncheckedCreateInput>
  /**
   * In case the orders_aliexpress_krym was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orders_aliexpress_krymUpdateInput, Prisma.orders_aliexpress_krymUncheckedUpdateInput>
}

/**
 * orders_aliexpress_krym delete
 */
export type orders_aliexpress_krymDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
  /**
   * Filter which orders_aliexpress_krym to delete.
   */
  where: Prisma.orders_aliexpress_krymWhereUniqueInput
}

/**
 * orders_aliexpress_krym deleteMany
 */
export type orders_aliexpress_krymDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders_aliexpress_kryms to delete
   */
  where?: Prisma.orders_aliexpress_krymWhereInput
  /**
   * Limit how many orders_aliexpress_kryms to delete.
   */
  limit?: number
}

/**
 * orders_aliexpress_krym without action
 */
export type orders_aliexpress_krymDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders_aliexpress_krym
   */
  select?: Prisma.orders_aliexpress_krymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders_aliexpress_krym
   */
  omit?: Prisma.orders_aliexpress_krymOmit<ExtArgs> | null
}
