/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSchedulesRouteImport } from './routes/_public/schedules'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as PublicTrackingIndexRouteImport } from './routes/_public/tracking/index'
import { Route as PublicShopCostCalculationOrderIndexRouteImport } from './routes/_public/shop-cost-calculation-order/index'
import { Route as PublicPickUpPointDeliveryOrderIndexRouteImport } from './routes/_public/pick-up-point-delivery-order/index'
import { Route as AuthenticatedDashboardRequestsIndexRouteImport } from './routes/_authenticated/dashboard/requests/index'
import { Route as AuthenticatedDashboardRequestsShopCostCalculationOrderRouteImport } from './routes/_authenticated/dashboard/requests/shop-cost-calculation-order'
import { Route as AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRouteImport } from './routes/_authenticated/dashboard/requests/pick-up-point-delivery-order'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSchedulesRoute = PublicSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicTrackingIndexRoute = PublicTrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopCostCalculationOrderIndexRoute =
  PublicShopCostCalculationOrderIndexRouteImport.update({
    id: '/shop-cost-calculation-order/',
    path: '/shop-cost-calculation-order/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPickUpPointDeliveryOrderIndexRoute =
  PublicPickUpPointDeliveryOrderIndexRouteImport.update({
    id: '/pick-up-point-delivery-order/',
    path: '/pick-up-point-delivery-order/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AuthenticatedDashboardRequestsIndexRoute =
  AuthenticatedDashboardRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRequestsShopCostCalculationOrderRoute =
  AuthenticatedDashboardRequestsShopCostCalculationOrderRouteImport.update({
    id: '/requests/shop-cost-calculation-order',
    path: '/requests/shop-cost-calculation-order',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute =
  AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRouteImport.update({
    id: '/requests/pick-up-point-delivery-order',
    path: '/requests/pick-up-point-delivery-order',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth': typeof PublicAuthRoute
  '/schedules': typeof PublicSchedulesRoute
  '/': typeof PublicIndexRoute
  '/pick-up-point-delivery-order': typeof PublicPickUpPointDeliveryOrderIndexRoute
  '/shop-cost-calculation-order': typeof PublicShopCostCalculationOrderIndexRoute
  '/tracking': typeof PublicTrackingIndexRoute
  '/dashboard/requests/pick-up-point-delivery-order': typeof AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute
  '/dashboard/requests/shop-cost-calculation-order': typeof AuthenticatedDashboardRequestsShopCostCalculationOrderRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth': typeof PublicAuthRoute
  '/schedules': typeof PublicSchedulesRoute
  '/': typeof PublicIndexRoute
  '/pick-up-point-delivery-order': typeof PublicPickUpPointDeliveryOrderIndexRoute
  '/shop-cost-calculation-order': typeof PublicShopCostCalculationOrderIndexRoute
  '/tracking': typeof PublicTrackingIndexRoute
  '/dashboard/requests/pick-up-point-delivery-order': typeof AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute
  '/dashboard/requests/shop-cost-calculation-order': typeof AuthenticatedDashboardRequestsShopCostCalculationOrderRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_public/auth': typeof PublicAuthRoute
  '/_public/schedules': typeof PublicSchedulesRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/pick-up-point-delivery-order/': typeof PublicPickUpPointDeliveryOrderIndexRoute
  '/_public/shop-cost-calculation-order/': typeof PublicShopCostCalculationOrderIndexRoute
  '/_public/tracking/': typeof PublicTrackingIndexRoute
  '/_authenticated/dashboard/requests/pick-up-point-delivery-order': typeof AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute
  '/_authenticated/dashboard/requests/shop-cost-calculation-order': typeof AuthenticatedDashboardRequestsShopCostCalculationOrderRoute
  '/_authenticated/dashboard/requests/': typeof AuthenticatedDashboardRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/schedules'
    | '/'
    | '/pick-up-point-delivery-order'
    | '/shop-cost-calculation-order'
    | '/tracking'
    | '/dashboard/requests/pick-up-point-delivery-order'
    | '/dashboard/requests/shop-cost-calculation-order'
    | '/dashboard/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/auth'
    | '/schedules'
    | '/'
    | '/pick-up-point-delivery-order'
    | '/shop-cost-calculation-order'
    | '/tracking'
    | '/dashboard/requests/pick-up-point-delivery-order'
    | '/dashboard/requests/shop-cost-calculation-order'
    | '/dashboard/requests'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/auth'
    | '/_public/schedules'
    | '/_public/'
    | '/_public/pick-up-point-delivery-order/'
    | '/_public/shop-cost-calculation-order/'
    | '/_public/tracking/'
    | '/_authenticated/dashboard/requests/pick-up-point-delivery-order'
    | '/_authenticated/dashboard/requests/shop-cost-calculation-order'
    | '/_authenticated/dashboard/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/schedules': {
      id: '/_public/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof PublicSchedulesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/tracking/': {
      id: '/_public/tracking/'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof PublicTrackingIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop-cost-calculation-order/': {
      id: '/_public/shop-cost-calculation-order/'
      path: '/shop-cost-calculation-order'
      fullPath: '/shop-cost-calculation-order'
      preLoaderRoute: typeof PublicShopCostCalculationOrderIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/pick-up-point-delivery-order/': {
      id: '/_public/pick-up-point-delivery-order/'
      path: '/pick-up-point-delivery-order'
      fullPath: '/pick-up-point-delivery-order'
      preLoaderRoute: typeof PublicPickUpPointDeliveryOrderIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/dashboard/requests/': {
      id: '/_authenticated/dashboard/requests/'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/requests/shop-cost-calculation-order': {
      id: '/_authenticated/dashboard/requests/shop-cost-calculation-order'
      path: '/requests/shop-cost-calculation-order'
      fullPath: '/dashboard/requests/shop-cost-calculation-order'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsShopCostCalculationOrderRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/requests/pick-up-point-delivery-order': {
      id: '/_authenticated/dashboard/requests/pick-up-point-delivery-order'
      path: '/requests/pick-up-point-delivery-order'
      fullPath: '/dashboard/requests/pick-up-point-delivery-order'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute: typeof AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute
  AuthenticatedDashboardRequestsShopCostCalculationOrderRoute: typeof AuthenticatedDashboardRequestsShopCostCalculationOrderRoute
  AuthenticatedDashboardRequestsIndexRoute: typeof AuthenticatedDashboardRequestsIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute:
      AuthenticatedDashboardRequestsPickUpPointDeliveryOrderRoute,
    AuthenticatedDashboardRequestsShopCostCalculationOrderRoute:
      AuthenticatedDashboardRequestsShopCostCalculationOrderRoute,
    AuthenticatedDashboardRequestsIndexRoute:
      AuthenticatedDashboardRequestsIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAuthRoute: typeof PublicAuthRoute
  PublicSchedulesRoute: typeof PublicSchedulesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPickUpPointDeliveryOrderIndexRoute: typeof PublicPickUpPointDeliveryOrderIndexRoute
  PublicShopCostCalculationOrderIndexRoute: typeof PublicShopCostCalculationOrderIndexRoute
  PublicTrackingIndexRoute: typeof PublicTrackingIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRoute: PublicAuthRoute,
  PublicSchedulesRoute: PublicSchedulesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPickUpPointDeliveryOrderIndexRoute:
    PublicPickUpPointDeliveryOrderIndexRoute,
  PublicShopCostCalculationOrderIndexRoute:
    PublicShopCostCalculationOrderIndexRoute,
  PublicTrackingIndexRoute: PublicTrackingIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
