
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model mobile_phone
 * 
 */
export type mobile_phone = Prisma.mobile_phoneModel
/**
 * Model orders_aist
 * 
 */
export type orders_aist = Prisma.orders_aistModel
/**
 * Model orders_aliexpress
 * 
 */
export type orders_aliexpress = Prisma.orders_aliexpressModel
/**
 * Model orders_aliexpress_krym
 * 
 */
export type orders_aliexpress_krym = Prisma.orders_aliexpress_krymModel
/**
 * Model orders_banki_rf
 * 
 */
export type orders_banki_rf = Prisma.orders_banki_rfModel
/**
 * Model orders_call_back
 * 
 */
export type orders_call_back = Prisma.orders_call_backModel
/**
 * Model orders_call_backDO
 * 
 */
export type orders_call_backDO = Prisma.orders_call_backDOModel
/**
 * Model orders_call_backGO
 * 
 */
export type orders_call_backGO = Prisma.orders_call_backGOModel
/**
 * Model orders_cart
 * 
 */
export type orders_cart = Prisma.orders_cartModel
/**
 * Model orders_commers
 * 
 */
export type orders_commers = Prisma.orders_commersModel
/**
 * Model orders_doski
 * 
 */
export type orders_doski = Prisma.orders_doskiModel
/**
 * Model orders_dostavka_ali
 * 
 */
export type orders_dostavka_ali = Prisma.orders_dostavka_aliModel
/**
 * Model orders_dostavka_rus
 * 
 */
export type orders_dostavka_rus = Prisma.orders_dostavka_rusModel
/**
 * Model orders_fromabroad
 * 
 */
export type orders_fromabroad = Prisma.orders_fromabroadModel
/**
 * Model orders_hotline
 * 
 */
export type orders_hotline = Prisma.orders_hotlineModel
/**
 * Model orders_iz_rf
 * 
 */
export type orders_iz_rf = Prisma.orders_iz_rfModel
/**
 * Model orders_iz_krim_ldnr
 * 
 */
export type orders_iz_krim_ldnr = Prisma.orders_iz_krim_ldnrModel
/**
 * Model orders_sadovod
 * 
 */
export type orders_sadovod = Prisma.orders_sadovodModel
/**
 * Model orders_temernik
 * 
 */
export type orders_temernik = Prisma.orders_temernikModel
/**
 * Model zabor_commerc
 * 
 */
export type zabor_commerc = Prisma.zabor_commercModel
/**
 * Model zabor_gruza
 * 
 */
export type zabor_gruza = Prisma.zabor_gruzaModel
/**
 * Model zabor_gruzaDNR
 * 
 */
export type zabor_gruzaDNR = Prisma.zabor_gruzaDNRModel
/**
 * Model zabor_gruzaKrym
 * 
 */
export type zabor_gruzaKrym = Prisma.zabor_gruzaKrymModel
/**
 * Model zabor_gruzaLNR
 * 
 */
export type zabor_gruzaLNR = Prisma.zabor_gruzaLNRModel
/**
 * Model zayvka_form
 * 
 */
export type zayvka_form = Prisma.zayvka_formModel
